"use client";
import type {ReactNode} from 'react';
import {Search,ChevronLeft,ChevronRight,Download,CheckCircle2} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {initials,money,type Learner,type Order} from '@/lib/admin-data';
export function Action({children,onClick,primary=false,disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;primary?:boolean;disabled?:boolean;type?:'button'|'submit'}){return <button type={type} className={'action '+(primary?'primary':'')} disabled={disabled} onClick={onClick}>{children}</button>}
export function Pick({value,values,onChange,label}:{value:string;values:string[];onChange:(v:string)=>void;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
export function FilterTabs({value,values,onChange}:{value:string;values:string[];onChange:(v:string)=>void}){return <Tabs value={value} onValueChange={onChange} className="filter-tabs"><TabsList>{values.map(v=><TabsTrigger key={v} value={v}>{v}</TabsTrigger>)}</TabsList></Tabs>}
export function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="search-box"><Search size={15}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}>×</button>}</label>}
export function NoResults({clear}:{clear:()=>void}){return <Empty className="empty-state"><EmptyHeader><Search/><EmptyTitle>No matching results</EmptyTitle><EmptyDescription>Your filters returned no records. Clear filters or change the date range.</EmptyDescription></EmptyHeader><Action onClick={clear}>Clear filters</Action></Empty>}
export function Pager({page,total,size,onChange}:{page:number;total:number;size:number;onChange:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/size));return <div className="pager"><span>{total?`${(page-1)*size+1}–${Math.min(page*size,total)}`:'0'} of {total}</span><Pagination><PaginationContent><PaginationItem><button aria-label="Previous page" disabled={page===1} onClick={()=>onChange(page-1)}><ChevronLeft size={15}/></button></PaginationItem>{Array.from({length:Math.min(3,pages)},(_,i)=>Math.min(Math.max(1,page-1),Math.max(1,pages-2))+i).map(p=><PaginationItem key={p}><button className={page===p?'selected':''} aria-label={'Page '+p} aria-current={p===page?'page':undefined} onClick={()=>onChange(p)}>{p}</button></PaginationItem>)}<PaginationItem><button aria-label="Next page" disabled={page===pages} onClick={()=>onChange(page+1)}><ChevronRight size={15}/></button></PaginationItem></PaginationContent></Pagination></div>}
export function Badge({children}:{children:ReactNode}){return <span className={'badge '+(['Paid','Lifetime','Delivered','Read','Published','Reconciled'].includes(String(children))?'success':'')}>{children}</span>}
export function Avatar({learner}:{learner:Learner}){return <span className="avatar">{initials(learner.name)}</span>}
export function FinanceTable({learners,orders,mode,selected,onSelect,query,status,method,page,setPage,clear}:{learners:Learner[];orders:Order[];mode:string;selected:string;onSelect:(id:string,order?:string)=>void;query:string;status:string;method:string;page:number;setPage:(n:number)=>void;clear:()=>void}){
 const transaction=mode==='Transactions';const q=query.toLowerCase();const list=transaction?orders.filter(o=>{const p=learners.find(l=>l.id===o.learnerId)!;return (p.name+p.handle+p.telegram+o.id).toLowerCase().includes(q)&&(status==='Status: All'||o.status===status)&&(method==='Method: All'||o.method===method);}):learners.filter(p=>(p.name+p.handle+p.telegram+(orders.find(o=>o.learnerId===p.id)?.id||'')).toLowerCase().includes(q)&&(status==='Status: All'||p.payment===status)&&(method==='Method: All'||p.method===method));
 const size=transaction?5:6;const current=list.slice((page-1)*size,page*size);
 return <div className="finance-list"><div className="mobile-finance-list">{current.map(row=>{const o=transaction?row as Order:undefined;const p=transaction?learners.find(l=>l.id===o!.learnerId)!:row as Learner;return <button key={row.id} onClick={()=>onSelect(p.id,o?.id)} className="mobile-finance-row"><Avatar learner={p}/><div><strong>{p.name}</strong><small>{transaction?o!.id:(p.method+" · "+p.joined)}</small><Badge>{transaction?o!.status:p.access}</Badge></div><div className="right"><strong className="mono">{(o?.amount||p.amount)?"UZS "+money(o?.amount||p.amount):"Never paid"}</strong><small>{o?.status||p.payment}</small></div><ChevronRight size={14}/></button>;})}</div>{list.length===0?<NoResults clear={clear}/>:<Table className="finance-table"><TableHeader><TableRow>{(transaction?['Order','Learner / gateway','Created','Paid / cancelled','Amount UZS','Method','Status','']:['Learner','Registered','Method','Total paid','Payment','Last paid','Access','']).map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{current.map(row=>{const o=transaction?row as Order:undefined;const p=transaction?learners.find(l=>l.id===o!.learnerId)!:row as Learner;return <TableRow key={row.id} data-selected={selected===p.id} onClick={()=>onSelect(p.id,o?.id)}>{transaction?<><TableCell className="mono">{o!.id}</TableCell><TableCell><strong>{p.name}</strong><small>Gateway: WLCM</small></TableCell><TableCell>{new Date(o!.created).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})} 14:29</TableCell><TableCell>{o!.paid}</TableCell><TableCell className="mono">{money(o!.amount)}</TableCell><TableCell>{o!.method}</TableCell><TableCell><Badge>{o!.status}</Badge></TableCell></>:<><TableCell><div className="person"><Avatar learner={p}/><div><strong>{p.name}</strong><small>{p.handle?'@'+p.handle:'ID '+p.telegram}</small></div></div></TableCell><TableCell>{new Date(p.joined).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</TableCell><TableCell>{p.method}</TableCell><TableCell className="mono">{p.amount?money(p.amount):'—'}</TableCell><TableCell><Badge>{p.payment}</Badge></TableCell><TableCell>{p.lastPaid}</TableCell><TableCell><Badge>{p.access}</Badge></TableCell></>}<TableCell><button aria-label={'Open '+(o?.id||p.name)} onClick={e=>{e.stopPropagation();onSelect(p.id,o?.id);}}><ChevronRight size={16}/></button></TableCell></TableRow>})}</TableBody></Table>}
 <Pager page={page} total={list.length} size={size} onChange={setPage}/></div>;
}
export function exportCsv(filename:string,rows:Record<string,unknown>[]){if(!rows.length)return false;const keys=Object.keys(rows[0]);const quote=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const blob=new Blob(['\ufeff'+[keys,...rows.map(row=>keys.map(k=>row[k]))].map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}

