'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type Summary={period:{start:string;end:string};learnersTotal:number;newLearners:number;activeLearners:number;completedLessons:number;paidOrders:number;revenueTiyin:string;previousRevenueTiyin:string;daily:{date:string;completedLessons:number;revenueTiyin:string}[];paymentMethods:{method:string;count:number;revenueTiyin:string}[];products:{sectionId:string;title:string;count:number;revenueTiyin:string}[];notificationCreated:number;notificationRead:number};
export type Learning={period:{start:string;end:string};cohort:string;funnel:{stage:string;count:number}[];activeLearners:number;completedLessons:number;completionRate:number|null;daily:{date:string;completedLessons:number}[];assessment:{attempts:number;passed:number;passRate:number|null};writing:{submissions:number;passed:number;passRate:number|null};ratings:{count:number;average:number|null};bottlenecks:{lessonId:string;title:string;started:number;unfinished:number;completionRate:number|null}[]};
export type LearnerAnalytics={learnerId:string;catalogAccess:boolean;sectionAccess:{sectionId:string;title:string;source:string}[];startedLessons:number;completedLessons:number;completionRate:number|null;items:{lessonId:string;title:string;completed:boolean;updatedAt:string}[];total:number;limit:number;offset:number;hasMore:boolean};
export function money(tiyin?:string){if(tiyin===undefined)return '—';const value=BigInt(tiyin);return (value/BigInt(100)).toLocaleString('en-US')+'.'+(value%BigInt(100)).toString().padStart(2,'0');}
export function percent(value?:number|null){return value==null?'—':value.toLocaleString('en-US',{maximumFractionDigits:1})+'%';}
export function analyticsValues(s?:Summary,l?:Learning,p?:LearnerAnalytics):Record<string,string>{
 const values:Record<string,string>={};const n=(v?:number)=>v===undefined?'—':v.toLocaleString('en-US');
 if(s){Object.assign(values,{'Date Range Label':s.period.start+' – '+s.period.end,'Active Learners Value':n(s.activeLearners),'Active Learners Delta':'In selected period','Lessons Completed Value':n(s.completedLessons),'Lessons Completed Delta':'Saved completions','Paid Access Value':money(s.revenueTiyin),'Paid Access Delta':'UZS · gross paid','Net Revenue Label':'GROSS COLLECTED REVENUE','Net Revenue Value':'UZS '+money(s.revenueTiyin),'Paid Orders Value':n(s.paidOrders),'Paid Orders Detail':'Paid in selected period','Average Order Value':'UZS '+money(s.paidOrders?(BigInt(s.revenueTiyin)/BigInt(s.paidOrders)).toString():'0'),'Average Order Detail':'Paid orders only','Gross Volume Value':'UZS '+money(s.revenueTiyin),'Gross Volume Detail':'Fees and refunds not deducted','Revenue Comparison':'vs previous equal period','Revenue Trend Title':'Daily collected revenue','Revenue Trend Subtitle':'Paid UZS orders by payment date','Revenue By Course Total Label':'Total · UZS '+money(s.revenueTiyin),'Active Learners Metric Value':n(s.activeLearners),'Active Learners Metric Label':'Active in period','Active Learners Metric Delta':percent(s.learnersTotal?s.activeLearners/s.learnersTotal*100:null),'Registered Learners Metric Delta':n(s.newLearners)+' new in period','Sent today Message Stat Label':'Inbox records created','Sent today Message Stat Value':n(s.notificationCreated),'Sent today Message Stat Detail':'In selected period','Read Message Stat Value':n(s.notificationRead),'Read Message Stat Detail':'Read in Mini App','Live Activity Label':'Saved activity · UTC'});
 const prev=Number(s.previousRevenueTiyin);values['Revenue Growth Label']=prev?percent((Number(s.revenueTiyin)-prev)/prev*100):'No prior revenue';
 for(let i=0;i<4;i++){const product=s.products[i],method=s.paymentMethods[i];Object.assign(values,{['Course Name '+(i+1)]:product?.title??'—',['Course Revenue Amount '+(i+1)]:product?'UZS '+money(product.revenueTiyin):'—',['Course Revenue Share '+(i+1)]:product?percent(Number(s.revenueTiyin)?Number(product.revenueTiyin)/Number(s.revenueTiyin)*100:null):'—',['Method Name '+(i+1)]:method?.method??'—',['Method Amount '+(i+1)]:method?'UZS '+money(method.revenueTiyin):'—',['Method Share '+(i+1)]:method?percent(Number(s.revenueTiyin)?Number(method.revenueTiyin)/Number(s.revenueTiyin)*100:null):'—'});}}
 if(l){Object.assign(values,{'Active learners Learning Stat Value':n(l.activeLearners),'Active learners Learning Stat Detail':'Progress updated in period','Lessons completed Learning Stat Value':n(l.completedLessons),'Lessons completed Learning Stat Detail':'Saved completions','Completion rate Learning Stat Value':percent(l.completionRate),'Completion rate Learning Stat Detail':'Completed / started learners','Learning Funnel Title':'Cohort learning funnel','Learning Funnel Conversion Label':percent(l.completionRate)+' complete','Weekly Activity Subtitle':'Saved completions · selected UTC dates','Weekly Activity Peak':'Select a bar to inspect','Avg score Quality Label':'Quiz pass rate','Avg score Quality Value':percent(l.assessment.passRate),'Retries Quality Label':'Writing pass rate','Retries Quality Value':percent(l.writing.passRate),'Rated Quality Value':l.ratings.average?.toFixed(1)??'—','Assessment Quality Note':n(l.assessment.attempts)+' attempts · '+n(l.writing.submissions)+' writing submissions','Learning Insights Count Label':n(l.bottlenecks.length)});for(let i=0;i<4;i++)Object.assign(values,{['Learning Issue Title '+i]:l.bottlenecks[i]?.title??'No additional bottleneck',['Learning Issue Detail '+i]:l.bottlenecks[i]?n(l.bottlenecks[i].unfinished)+' unfinished of '+n(l.bottlenecks[i].started)+' started':'—'});}
 if(p)Object.assign(values,{'Completed Metric Value':n(p.completedLessons)+' lessons','Access Metric Value':p.catalogAccess?'Whole catalog':n(p.sectionAccess.length)+' sections','Access Learner Fact Value':p.catalogAccess?'Whole catalog · Lifetime':p.sectionAccess.map(a=>a.title).join(', ')||'No paid access','Lessons Learner Fact Value':n(p.completedLessons)+' / '+n(p.startedLessons)+' started lessons','Selected Learner Profile Status Label':'REGISTERED'});
 return values;
}
export function DailyChart({items,onSelect,label}:{items:{date:string;value:number}[];onSelect:(day:string)=>void;label:string}){
 const max=Math.max(1,...items.map(d=>d.value));
 return <div className="analytics-chart" aria-label={label}>{items.map(d=><button key={d.date} title={`${d.date}: ${d.value.toLocaleString('en-US')}`} aria-label={`${label} ${d.date}: ${d.value.toLocaleString('en-US')}`} onClick={()=>onSelect(d.date)}><span className="analytics-bar" style={{height:`${Math.max(d.value?2:0,100*d.value/max)}%`}}/><small>{d.date.slice(5)}</small></button>)}</div>;
}
export function ActivityDialog({query,onClose,onLearner}:{query:string;onClose:()=>void;onLearner:(id:string)=>void}){
 const [offset,setOffset]=useState(0),[reload,setReload]=useState(0),[error,setError]=useState('');
 const [result,setResult]=useState<{key:string;items:{learnerId:string;username:string|null;title:string;completedAt:string|null;completed:boolean}[];total:number;hasMore:boolean}|null>(null);
 const key=query+':'+offset+':'+reload;
 useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams(query);params.set('limit','25');params.set('offset',String(offset));fetch('/api/admin/analytics-activity?'+params,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)])}).then(async r=>{if(r.status===401)window.location.replace('/login');const data=await r.json();if(!r.ok)throw new Error(data.error?.message??'Could not load activity.');if(!controller.signal.aborted){setResult({...data,key});setError('');}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[query,offset,reload,key]);
 return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="admin-dialog pencil-dialog"><DialogHeader><DialogTitle>{new URLSearchParams(query).get('activityStatus')==='unfinished'?'Intervention queue':'Learning activity'}</DialogTitle><DialogDescription>Saved lesson activity for the selected UTC dates and registration cohort.</DialogDescription></DialogHeader>{error?<p role="alert">{error}<button onClick={()=>{setError('');setReload(n=>n+1);}}>Retry activity</button></p>:result?.key!==key?<p role="status">Loading activity…</p>:<><p>{result.total} lesson records</p>{!result.items.length&&<p>No matching activity in this period.</p>}{result.items.map((r,i)=><button className="pencil-field" key={r.learnerId+':'+i} onClick={()=>onLearner(r.learnerId)}>{r.title}<div>{r.username?'@'+r.username:r.learnerId} · {r.completedAt??'In progress'}</div></button>)}</>}<div className="pencil-dialog-actions"><button disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-25))}>Previous</button><button disabled={result?.key!==key||!result?.hasMore} onClick={()=>setOffset(n=>n+25)}>Next</button><button onClick={onClose}>Close</button></div></DialogContent></Dialog>;
}
