'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type BusinessMode='Manage access'|'Reconcile case'|'Learning intervention';
type Permissions={canGrantCatalogAccess:boolean;canCloseReconciliation:boolean;canCreateIntervention:boolean};
type LearnerState={learnerId:string;accessState:'lifetime'|'no_access';accessVersion:number;accessOverride:boolean;catalogGrant:null|{version:number;revokedAt:string|null;grantedAt:string};followUpVersion:number;permissions:Permissions};
type Case={id:string;learnerId:string;orderId:string|null;status:string;issue:string;version:number;closureNote:string|null};
type Page={items:Case[];total:number;limit:number;offset:number;hasMore:boolean};
export function BusinessDialog({mode,learnerId,learnerName,csrf,onClose,onSaved}:{mode:BusinessMode;learnerId?:string;learnerName?:string;csrf:string;onClose:()=>void;onSaved?:()=>void}){
 const [state,setState]=useState<LearnerState|null>(null),[permissions,setPermissions]=useState<Permissions|null>(null),[page,setPage]=useState<Page|null>(null),[selected,setSelected]=useState<Case|null>(null);
 const [reason,setReason]=useState(''),[title,setTitle]=useState(''),[due,setDue]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[discard,setDiscard]=useState(false),[confirm,setConfirm]=useState(false),[saved,setSaved]=useState(false);
 const [offset,setOffset]=useState(0),[reload,setReload]=useState(0);
 const [access,setAccess]=useState<'lifetime'|'no_access'>('lifetime'),[passwordReady,setPasswordReady]=useState(false);
 const passwordInput=useRef<HTMLInputElement|null>(null);
 function clearPassword(){if(passwordInput.current)passwordInput.current.value='';setPasswordReady(false);}
 useEffect(()=>()=>{if(passwordInput.current)passwordInput.current.value='';},[]);
 const request=useRef<{fingerprint:string;id:string}|null>(null);
 const dirty=!!(reason||title||due)&&!saved;
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{const controller=new AbortController();let active=true;
  async function read(path:string){const response=await fetch('/api/admin/'+path,{credentials:'same-origin',cache:'no-store',signal:controller.signal});if(response.status===401){window.location.replace('/login');throw new Error('Sign in required.');}const data=await response.json();if(!response.ok)throw new Error('Could not load records.');return data;}
  async function load(){try{if(mode==='Reconcile case'){const [cases,permission]=await Promise.all([read('business-cases?'+new URLSearchParams({limit:'25',offset:String(offset)})),read('business-permissions')]);if(active){setPage(cases);setPermissions(permission);setSelected(null);}}else{if(!learnerId)throw new Error('Select a learner first.');const result=await read('business-state?'+new URLSearchParams({learnerId}));if(active){setState(result);setPermissions(result.permissions);if(mode==='Manage access')setAccess(result.accessState==='lifetime'&&!result.accessOverride?'no_access':'lifetime');}}}catch{if(active)setError(mode==='Manage access'?'Ma’lumotlarni yuklab bo‘lmadi.':'Could not load records.');}finally{if(active)setLoading(false);}}
  void load();return()=>{active=false;controller.abort();};
 },[mode,learnerId,offset,reload]);
 function close(){if(busy)return;clearPassword();if(dirty)setDiscard(true);else onClose();}
 function refresh(){clearPassword();setState(null);setPermissions(null);setLoading(true);setError('');setConflict(false);setConfirm(false);request.current=null;setReload(v=>v+1);}
 const allowed=mode==='Manage access'?permissions?.canGrantCatalogAccess:mode==='Reconcile case'?permissions?.canCloseReconciliation:permissions?.canCreateIntervention;
 const activeGrant=state?.accessState==='lifetime'&&!state.accessOverride;
 const revoking=mode==='Manage access'&&access==='no_access';
 const manageMode=mode==='Manage access';
 const targetName=learnerName||`ID ${learnerId??'—'}`;
 const proPrompt=revoking?`Siz ${targetName} (ID: ${learnerId??'—'}) ning obunasini bekor qilmoqchisiz.`:`Siz ${targetName} (ID: ${learnerId??'—'}) ni PRO ga o‘tkazmoqchisiz.`;
 const accessReason=revoking?'Administrator tomonidan obunani bekor qilish tasdiqlandi.':'Administrator tomonidan 1 yillik obuna berildi.';
 const valid=manageMode?!!state&&(revoking?!state.accessOverride:!activeGrant):reason.trim().length>=20&&reason.length<=1000&&(mode!=='Learning intervention'||title.trim().length>=3)&&(mode!=='Reconcile case'||!!selected);
 async function save(){if((!manageMode&&!confirm)||!valid||!allowed||busy||(revoking&&!passwordReady))return;setBusy(true);setError('');
  const body:Record<string,unknown>=mode==='Reconcile case'?{caseId:selected!.id,baseVersion:selected!.version,note:reason}:mode==='Manage access'?{learnerId,baseVersion:state!.accessVersion,reason:accessReason}:{learnerId,baseVersion:state!.followUpVersion,reason,taskTitle:title,dueAt:due?new Date(due).toISOString():null};
  const action=mode==='Manage access'?(revoking?'business-revoke':'business-grant'):mode==='Reconcile case'?'business-close':'business-intervention';
  // Idempotency identity deliberately excludes the write-only password.
  const fingerprint=JSON.stringify({action,...body});if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};body.requestId=request.current.id;
  if(revoking)body.password=passwordInput.current?.value??'';
  const payload=JSON.stringify(body);delete body.password;clearPassword();
  try{
   const response=await fetch('/api/admin/'+action,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-Admin-CSRF':csrf},body:payload,signal:AbortSignal.timeout(12000)});
   const result=await response.json();
   if(response.status===401){if(result.error?.code==='admin_reauthentication_failed'){setError(manageMode?'Joriy administrator paroli noto‘g‘ri. Qayta kiriting.':'Current administrator password is incorrect. Enter it again.');return;}window.location.replace('/login');return;}
   if(response.status===409){setConflict(true);setConfirm(false);return;}
   if(!response.ok){setError(manageMode?(response.status===429?'Juda ko‘p urinish bo‘ldi. Besh daqiqadan keyin qayta urinib ko‘ring.':response.status===403?'Ruxsat yo‘q yoki administrator sessiyasi tasdiqlanmadi.':'Saqlab bo‘lmadi. Qayta urinib ko‘ring.'):(response.status===429?'Too many attempts. Wait five minutes before retrying.':response.status===403?'Permission denied or session verification failed. Reload before retrying.':'Could not save. Review and retry the same request safely.'));return;}
   setSaved(true);setConfirm(false);setLoading(true);setReload(v=>v+1);onSaved?.();
   if(manageMode){onClose();return;}
  }catch{setError(manageMode?'Natijani tasdiqlab bo‘lmadi. Xavfsiz tarzda qayta urinib ko‘ring.':'Could not confirm the result. Retry the same request safely or reload the record.');}finally{clearPassword();setBusy(false);}
 }
 const heading=discard?(manageMode?'Saqlanmagan o‘zgarish':'Unsaved changes'):saved?(manageMode?'Saqlandi':'Changes saved'):conflict?(manageMode?'Ma’lumot o‘zgargan':'Record changed'):confirm?(mode==='Reconcile case'?'Resolve discrepancy':'Confirm intervention'):manageMode?'PRO qilish':mode;
 return <Dialog open onOpenChange={v=>{if(!v)close();}}><DialogContent className={manageMode?"pd-dialog pd-pro-dialog":"pd-dialog"} showCloseButton={false}><DialogHeader><DialogTitle>{heading}</DialogTitle><DialogDescription>{discard?(manageMode?'Kiritilgan o‘zgarish saqlanmadi.':'Your draft has not been saved.'):saved?(manageMode?'O‘zgarish audit tarixi bilan saqlandi.':'The change was committed with an immutable audit record.'):conflict?(manageMode?'Ma’lumot boshqa administrator tomonidan o‘zgartirilgan. Qayta yuklab, yana urinib ko‘ring.':'This record changed. Reload the current version before reviewing and submitting again.'):manageMode?proPrompt:mode==='Reconcile case'?'Review payment and entitlement discrepancies.':'Create an internal note and a follow-up task.'}</DialogDescription></DialogHeader>
 {discard?<><p className="pd-feedback">{manageMode?'Faqat saqlanmagan o‘zgarish bekor qilinadi.':'Discarding removes only this unsaved draft.'}</p><div className="pd-dialog-actions"><button onClick={()=>setDiscard(false)}>{manageMode?'Davom etish':'Keep editing'}</button><button className="pd-button primary" onClick={onClose}>{manageMode?'O‘zgarishni bekor qilish':'Discard changes'}</button></div></>:saved?<>{loading?<p role="status">{manageMode?'Joriy holat tekshirilmoqda…':'Verifying current record…'}</p>:error?<p role="alert">{manageMode?`O‘zgarish saqlandi. ${error}`:`Change committed. ${error}`}</p>:<p className="pd-feedback">{mode==='Manage access'?(state?.accessOverride?'Obuna bekor qilindi. To‘lov tarixi va o‘quv natijalari saqlanib qoldi.':'1 yillik obuna faollashtirildi. Mavjud to‘lovlar va accesslar saqlanib qoldi.'):mode==='Reconcile case'?'The case is closed. Payment status and entitlements were preserved.':'The internal note and follow-up task were saved. No outbound message was sent.'}</p>}<div className="pd-dialog-actions">{error&&<button disabled={loading} onClick={refresh}>{manageMode?'Qayta tekshirish':'Retry verification'}</button>}<button className="pd-button primary" onClick={onClose}>{manageMode?'Yopish':'Done'}</button></div></>:conflict?<div className="pd-dialog-actions"><button onClick={close}>{manageMode?'Bekor qilish':'Cancel'}</button><button className="pd-button primary" onClick={refresh}>{manageMode?'Qayta yuklash':'Reload record'}</button></div>:<>
 {loading?<p role="status">{manageMode?'Ma’lumotlar yuklanmoqda…':'Loading records…'}</p>:<>
 {mode==='Reconcile case'&&!confirm&&<><div className="pd-field">Open cases{page?.items.length?<div>{page.items.map(item=><button aria-pressed={selected?.id===item.id} key={item.id} disabled={busy} onClick={()=>setSelected(item)}>{item.id} · Learner {item.learnerId}<br/>{item.issue}</button>)}</div>:<div>No open discrepancies.</div>}</div>{page&&<div className="pd-dialog-actions"><button disabled={busy||offset===0} onClick={()=>{setLoading(true);setOffset(Math.max(0,offset-25));}}>Previous</button><span>{page.total} cases</span><button disabled={busy||!page.hasMore} onClick={()=>{setLoading(true);setOffset(offset+25);}}>Next</button></div>}</>}
 {manageMode&&<><label className="pd-field">Tarif<select aria-label="Tarif" value={access} disabled={busy} onChange={e=>{clearPassword();setAccess(e.target.value as 'lifetime'|'no_access');setError('');}}><option value="lifetime">1 yillik obuna</option><option value="no_access">Obunani bekor qilish</option></select></label>{revoking&&<label className="pd-field">Joriy administrator paroli<input ref={passwordInput} aria-label="Joriy administrator paroli" type="password" autoComplete="current-password" required maxLength={256} disabled={busy} onChange={e=>setPasswordReady(e.target.value.length>0&&e.target.value.length<=256)}/><small>Obunani bekor qilishni tasdiqlash uchun parolingizni kiriting.</small></label>}</>}
 {mode==='Reconcile case'&&selected&&<div className="pd-field">Selected case<div>{selected.id}<br/>{selected.issue}<br/>Learner {selected.learnerId}</div></div>}
 {mode==='Learning intervention'&&<><label className="pd-field">Follow-up task<input aria-label="Follow-up task" required minLength={3} maxLength={180} disabled={busy||confirm} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="pd-field">Due date (optional)<input aria-label="Due date (optional)" type="datetime-local" disabled={busy||confirm} value={due} onChange={e=>setDue(e.target.value)}/></label><p className="pd-feedback">Administrators only. No learner notification is sent.</p></>}
 {!manageMode&&<label className="pd-field">{mode==='Reconcile case'?'Closure note':'Reason'}<textarea aria-label={mode==='Reconcile case'?'Closure note':'Reason'} required minLength={20} maxLength={1000} disabled={busy||confirm} value={reason} onChange={e=>setReason(e.target.value)}/><small>Required: 20–1000 characters. {reason.trim().length}/1000</small></label>}
 {mode==='Reconcile case'&&<p className="pd-feedback">Closing a case records your explanation. Payment status and access are not changed.</p>}
 {permissions&&!allowed&&<p role="status">{manageMode?'PRO qilish uchun ruxsat kerak.':'Permission for this business operation is required.'}</p>}
 </>}
 {error&&<p role="alert">{error}</p>}<div className="pd-dialog-actions"><button disabled={busy} onClick={confirm?()=>{clearPassword();setConfirm(false);}:close}>{confirm?'Back':manageMode?'Bekor qilish':'Cancel'}</button>{error&&!state&&!page?<button className="pd-button primary" disabled={loading} onClick={refresh}>Retry</button>:<button className="pd-button primary" disabled={loading||busy||!allowed||!valid||(manageMode&&revoking&&!passwordReady)} onClick={manageMode?()=>void save():confirm?()=>void save():()=>setConfirm(true)}>{busy?'Saving…':manageMode?'Tasdiqlash':confirm?(mode==='Reconcile case'?'Close case':'Save intervention'):'Review change'}</button>}</div>
 </>}
 </DialogContent></Dialog>;
}
