"use client";
import {createElement, useState, useEffect, useRef, type ReactNode} from 'react';
import {Menu,ArrowLeft,CheckCircle2,ChevronRight,Search,Download,RefreshCw,ShieldCheck,BookOpen,AlertTriangle,Copy,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {seedData,initials,money,type Learner,type Lesson,type AdminData} from '@/lib/admin-data';
import {Action,Pick,FilterTabs,SearchBox,NoResults,Pager,Badge,Avatar,FinanceTable,exportCsv} from './admin-controls';
import design from './design.json';
import {learningReport,reportingBounds} from '@/lib/reporting';
type N={tag:string;attrs:Record<string,string>;children:(N|string)[]};
const screens=design as unknown as Record<string,N>;
const routes:Record<string,string>={Overview:'bi8Au',Learners:'C5tZxu',Content:'DUfwI',Commerce:'uYGzD',Learning:'KNuM1',Messages:'nqETx'};
const byName:Record<string,N>={};function index(n:N|string){if(typeof n==='string')return;byName[n.attrs['data-pencil-name']]=n;n.children.forEach(index);}Object.values(screens).forEach(index);
function textOf(n:N|string):string{return typeof n==='string'?n:n.children.map(textOf).join(' ');}
type Modal={kind:string;title:string;block?:string;id?:string};
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
const courses=['Foundation','Self-study Assistant','Advanced Vocabulary','Extra Lessons'];
export default function Home(){
 const [route,setRoute]=useState('Overview');
 const [data,setData]=useState<AdminData>(seedData),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[updated,setUpdated]=useState(0);
 const [selected,setSelected]=useState('lr_1'),[orderId,setOrderId]=useState(''),[eventId,setEventId]=useState('evt_7K18'),[caseId,setCaseId]=useState('case_1');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[commerceTab,setCommerceTab]=useState('Learners & access'),[status,setStatus]=useState('Status: All'),[method,setMethod]=useState('Method: All'),[page,setPage]=useState(1),[sort,setSort]=useState('Last seen ↓');
 const [mobile,setMobile]=useState(false),[mobileDetail,setMobileDetail]=useState(false),[modal,setModal]=useState<Modal|null>(null),[modalError,setModalError]=useState(''),[confirm,setConfirm]=useState<Record<string,unknown>|null>(null);
 const [lesson,setLesson]=useState<Lesson>(()=>seedData().lessons[0]),[course,setCourse]=useState('Foundation'),[unit,setUnit]=useState(1),[dirty,setDirty]=useState(false);
 const [note,setNote]=useState(''),[reason,setReason]=useState(''),[access,setAccess]=useState('Lifetime'),[globalQuery,setGlobalQuery]=useState(''),[autoRefresh,setAutoRefresh]=useState(true),[dateRange,setDateRange]=useState('Last 30 days'),[dateStart,setDateStart]=useState('2026-09-01'),[dateEnd,setDateEnd]=useState('2026-09-30'),[cohort,setCohort]=useState('All cohorts'),[reviewed,setReviewed]=useState(false);
 const draggedBlock=useRef<string|null>(null); const fileRef=useRef<HTMLInputElement>(null);const latest=useRef({data,revision});latest.current={data,revision};
 const p=data.learners.find(l=>l.id===selected)||data.learners[0];const event=data.events.find(e=>e.id===eventId)||data.events[0];const eventPerson=data.learners.find(l=>l.id===event.learnerId)||p;
 const order=data.orders.find(o=>o.id===orderId&&o.learnerId===p.id)||data.orders.find(o=>o.learnerId===p.id);const currentCase=data.cases.find(c=>c.id===caseId)||data.cases[0];
 const report=learningReport(dateRange,cohort),bounds=reportingBounds(dateRange),customPeriod=dateRange!=='Last 30 days';
 const periodOrders=customPeriod?data.orders.filter(o=>o.created.slice(0,10)>=bounds.start&&o.created.slice(0,10)<=bounds.end):data.orders;
 const collected=periodOrders.filter(o=>o.status==='Paid').reduce((s,o)=>s+o.amount,0),paidOrders=periodOrders.filter(o=>o.status==='Paid').length;
 const changeQuery=(v:string)=>{setQuery(v);setPage(1);};const changeFilter=(v:string)=>{setFilter(v);setPage(1);};
 const clear=()=>{setQuery('');setFilter(route==='Messages'?'All events':'All');setStatus('Status: All');setMethod('Method: All');setPage(1);};
 async function refresh(quiet=false){if(!quiet)setLoading(true);try{const res=await fetch('/api/admin');const body=await res.json() as {data:AdminData;revision:number;error:string};if(!res.ok)throw new Error(body.error);setData(body.data);setRevision(body.revision);setUpdated(Date.now());setError('');if(!dirty)setLesson(prev=>body.data.lessons.find((l:Lesson)=>l.id===prev.id)||prev);}catch(e){setError(e instanceof Error?e.message:'Couldn’t load data');}finally{setLoading(false);}}
 useEffect(()=>{void refresh();const hash=location.hash.slice(1).split('/')[0];const key=Object.keys(routes).find(k=>k.toLowerCase()===hash);if(key)setRoute(key);const onHash=()=>{const key=Object.keys(routes).find(k=>k.toLowerCase()===location.hash.slice(1).split('/')[0]);if(key){setRoute(key);setFilter(key==='Messages'?'All events':'All');setQuery('');setPage(1);setMobileDetail(false);}};addEventListener('hashchange',onHash);return()=>removeEventListener('hashchange',onHash);},[]);
 useEffect(()=>{if(!autoRefresh)return;const id=setInterval(()=>{if(!modal)void refresh(true);},60000);return()=>clearInterval(id);},[autoRefresh,dirty,modal]);
 useEffect(()=>{if(!dirty)return;const protect=(e:BeforeUnloadEvent)=>{e.preventDefault();};addEventListener('beforeunload',protect);return()=>removeEventListener('beforeunload',protect);},[dirty]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{context.registerTool({name:'search_leap_learners',description:'Search learner records in the current LEAP workspace. Read only.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof (input as {query?:unknown}).query!=='string')throw new Error('query must be a string');const q=(input as {query:string}).query.toLowerCase();return latest.current.data.learners.filter(l=>(l.name+l.handle+l.telegram).toLowerCase().includes(q)).slice(0,20).map(l=>({id:l.id,name:l.name,access:l.access,progress:l.progress}));}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[]);
 function go(next:string){setRoute(next);setMobile(false);setMobileDetail(false);setQuery('');setFilter(next==='Messages'?'All events':'All');setPage(1);location.hash=next.toLowerCase();window.scrollTo({top:0});}
 function selectLearner(id:string,oid?:string){setSelected(id);setOrderId(oid||'');setMobileDetail(true);if(window.matchMedia("(max-width:767px)").matches)window.scrollTo({top:0});}
 function open(kind:string,title:string,block?:string){setModalError('');setModal({kind,title,block});setReason('');setReviewed(false);if(kind==='access')setAccess(p.access);}
 async function mutate(command:Record<string,unknown>){if(!revision){setModalError('Data is not available yet. Refresh and retry.');return false;}setSaving(true);setModalError('');try{const res=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision,command})});const b=await res.json() as {data:AdminData;revision:number;error:string};if(!res.ok)throw new Error(b.error);setData(b.data);setRevision(b.revision);setUpdated(Date.now());setError('');toast.success(command.action==='publish'?'Lesson published':'Changes saved');return true;}catch(e){const msg=e instanceof Error?e.message:'Could not save';setModalError(msg);toast.error(msg);return false;}finally{setSaving(false);}}
 async function saveLesson(){if(await mutate({action:'saveLesson',lesson})){setDirty(false);setLesson({...lesson,status:'In review',updated:new Date().toISOString()});return true;}return false;}
 function exportData(kind:string){const q=query.toLowerCase();let rows:Record<string,unknown>[];if(kind==='Messages')rows=data.events.filter(e=>(filter==='All events'||filter==='All'||e.category===filter)&&(e.title+data.learners.find(l=>l.id===e.learnerId)?.name+e.detail+e.orderId).toLowerCase().includes(q)).map(e=>({...e}));else if(kind==='Commerce')rows=periodOrders.filter(o=>(status==='Status: All'||o.status===status)&&(method==='Method: All'||o.method===method)&&(o.id+(data.learners.find(l=>l.id===o.learnerId)?.name||'')).toLowerCase().includes(q)).map(o=>({...o}));else if(kind==='Learners')rows=filteredLearners.map(({notes,...l})=>({...l,notes:notes.map(n=>n.text).join('; ')}));else rows=[{metric:'Active Learners',value:1284,period:dateRange},{metric:'Lessons Completed',value:8492,period:dateRange},{metric:'Paid Access (UZS)',value:186400000,period:dateRange},{metric:'Needs Attention',value:7,period:dateRange}];if(exportCsv('leap-'+kind.toLowerCase(),rows))toast.success('Report exported');else toast.info('No matching records to export');}
 const filteredLearners=data.learners.filter(l=>(l.name+l.handle+l.telegram).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||filter==='New'&&l.status.startsWith('New')||filter==='Paid'&&l.payment==='Paid'||filter==='No access'&&l.access==='No access'||filter==='Needs help'&&(l.status.includes('Needs')||l.payment==='Pending'||l.status==='Inactive'))).sort((a,b)=>sort==='Name A–Z'?a.name.localeCompare(b.name):sort==='Progress ↓'?b.progress-a.progress:0);
 const filteredEvents=data.events.filter(e=>(filter==='All events'||filter==='All'||filter===e.category)&&(e.title+e.detail+e.orderId+(data.learners.find(l=>l.id===e.learnerId)?.name||'')).toLowerCase().includes(query.toLowerCase()));
 function template(n:N,map:Record<string,string>,onClick?:()=>void):ReactNode{return render(n,{map,onClick,skip:true});}
 function learnerMap(l:Learner){return {'Madina Karimova':l.name,'@madina_k':'@'+l.handle,'MK':initials(l.name),'Active now':l.status,'68%':l.progress+'%','34 / 50 completed':Math.round(l.progress/2)+' / 50 completed','7 days':l.streak+' days','Foundation · lifetime':l.course+' · '+l.access.toLowerCase(),'@madina_k · joined 11 Sep 2026 · active now':(l.handle?'@'+l.handle:'ID '+l.telegram)+' · joined '+l.joined+' · '+l.status.toLowerCase()};}
 function render(n:N|string,ctx:{map?:Record<string,string>;onClick?:()=>void;skip?:boolean;parent?:string;insideButton?:boolean}={}):ReactNode{
  if(typeof n==='string')return ctx.map?.[n]??n;
  const name=n.attrs['data-pencil-name']||'',id=n.attrs['data-pencil-id'];let tag=n.tag;let content:ReactNode=undefined;let click:(()=>void)|undefined=ctx.onClick;let map=ctx.map;let disabled=false;
  const attrs:Record<string,unknown>={...n.attrs,key:id,className:n.attrs.class};delete attrs.class;
  if(name.startsWith('Production /'))attrs.className='design-screen '+n.attrs.class;
  if(name==='Navigation Utilities')content=<><button aria-label="Search everything" className="nav-icon" onClick={()=>open('search','Search LEAP')}><Search size={17}/></button><button aria-label="Notifications" className="nav-icon" onClick={()=>go('Messages')}>{render(n.children[1],{skip:true})}</button><button aria-label="Settings" className="nav-icon" onClick={()=>open('settings','Workspace settings')}>{render(n.children[2],{skip:true})}</button><button aria-label="Admin profile" className="nav-icon" onClick={()=>open('account','Admin profile')}>{render(n.children[3],{skip:true})}</button><button aria-label="Open navigation" className="mobile-menu nav-icon" onClick={()=>setMobile(true)}><Menu/></button></>;
  if(ctx.parent==='Navigation Utilities'&&ctx.skip){attrs.className='contents';}
  const nav=Object.keys(routes).find(x=>name===x+' Nav Item');if(nav){click=()=>go(nav);attrs.className+=' design-nav';attrs['aria-current']=route===nav?'page':undefined;}
  if(!ctx.skip){
   if(name==='Open Learner Link')attrs.className+=' readable-link';
   if(name==='Date Range Label')content=dateRange;
   if(name==='Foundation Progress Fill')return <Progress key={id} value={p.progress} className="h-[7px] w-full"/>;
   if(name==='Self-study Assistant Progress Fill')return <Progress key={id} value={Math.round(p.progress*32/68)} className="h-[7px] w-full"/>;
   if(name==='Advanced Vocabulary Progress Fill')return <Progress key={id} value={Math.round(p.progress*12/68)} className="h-[7px] w-full"/>;
   if(name==='Self-study Assistant Progress Value')content=Math.round(p.progress*32/68)+'%';
   if(name==='Advanced Vocabulary Progress Value')content=Math.round(p.progress*12/68)+'%';
   if(name==='Publish Readiness Progress')return <Progress key={id} className="h-2 w-full" value={lesson.passScore>=1?100:80}/>;
   if(name==='Lesson Editor Title')attrs.className+=' lesson-title-button';
   if(name==='Learner Attention Updated')content=updated?'Updated '+new Date(updated).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}):'Loading data…';
   if(name==='Published lessons Content Stat Value')content=String(746+data.audit.filter(a=>a.action==='publish').length);
   if(customPeriod){
    const values:Record<string,string>={'Active Learners Value':String(report.active),'Lessons Completed Value':money(report.completed),'Paid Access Value':(collected/1e6).toFixed(1)+'M','Net Revenue Value':'UZS '+(collected/1e6).toFixed(1)+'M','Paid Orders Value':String(paidOrders),'Average Order Value':'UZS '+(paidOrders?collected/paidOrders/1e6:0).toFixed(2)+'M','Gross Volume Value':'UZS '+(periodOrders.reduce((s,o)=>s+o.amount,0)/1e6).toFixed(1)+'M','Revenue By Course Total Label':'Total · UZS '+(collected/1e6).toFixed(1)+'M','Revenue Trend Subtitle':dateRange,'Revenue Comparison':'Selected reporting period','Learning Pulse Copy':report.completed+' lessons completed in this period.'};
    if(values[name]!==undefined)content=values[name];
    if(/Revenue Growth Label/.test(name))content=paidOrders+' paid';
    if(/Course Revenue Amount [1-4]$/.test(name)){const courseNames=['Foundation','Advanced Vocabulary','Self-study Assistant','Extra Lessons'];const i=Number(name.slice(-1))-1;const amount=periodOrders.filter(o=>o.status==='Paid'&&data.learners.find(l=>l.id===o.learnerId)?.course===courseNames[i]).reduce((s,o)=>s+o.amount,0);content='UZS '+(amount/1e6).toFixed(1)+'M';}
    if(/Course Revenue Share [1-4]$/.test(name)){const courseNames=['Foundation','Advanced Vocabulary','Self-study Assistant','Extra Lessons'];const i=Number(name.slice(-1))-1;const amount=periodOrders.filter(o=>o.status==='Paid'&&data.learners.find(l=>l.id===o.learnerId)?.course===courseNames[i]).reduce((s,o)=>s+o.amount,0);content=(collected?Math.round(amount/collected*100):0)+'%';}
    if(name==='Revenue Trend Chart')return <div key={id} className="period-revenue"><svg viewBox="0 0 700 170" role="img" aria-label="Revenue by day in the selected reporting period">{Array.from({length:7},(_,i)=>{const amount=periodOrders.filter(o=>o.status==='Paid'&&Number(o.created.slice(8,10))%7===i).reduce((s,o)=>s+o.amount,0);const values=Array.from({length:7},(_,j)=>periodOrders.filter(o=>o.status==='Paid'&&Number(o.created.slice(8,10))%7===j).reduce((s,o)=>s+o.amount,0));const height=amount/Math.max(1,...values)*140;return <g key={i}><rect x={i*100+10} y={145-height} width="75" height={height} rx="5" fill={i===6?'#00866b':'#7469e8'}/><text x={i*100+47} y="165" fill="#aeb5ce" fontSize="11" textAnchor="middle">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</text></g>;})}</svg>{periodOrders.length===0&&<small>No orders in this period.</small>}</div>;
   }
   if(route==='Learning'&&(customPeriod||cohort!=='All cohorts')){
    const values:Record<string,string>={'Active learners Learning Stat Value':String(report.active),'Lessons completed Learning Stat Value':money(report.completed),'Completion rate Learning Stat Value':report.rate+'%','Learning Funnel Conversion Label':report.rate+'% complete','Started a lesson Funnel Value':report.started+' lesson starts','Reached 50% Funnel Value':report.half+' observations','Completed Funnel Value':report.finished+' completions','Rated lesson Funnel Value':report.rated+' ratings','Learning Funnel Subtitle':cohort+' · '+dateRange,'Weekly Activity Subtitle':report.completed+' completions in the selected period'};if(values[name]!==undefined)content=values[name];
    if(name==='Weekly Activity Bars')return <div key={id} className="report-bars">{report.rows.slice(-7).map(r=><button key={r.date} title={r.date+': '+r.completed+' completions'} onClick={()=>open('chart',r.date)}><svg viewBox="0 0 60 200"><rect x="5" y={190-r.completed/400*180} width="50" height={r.completed/400*180} rx="5" fill="#7469e8"/></svg><small>{r.date.slice(5)}</small></button>)}{report.rows.length===0&&<p>No learning observations in this period.</p>}</div>;
   }
   if(/ Activity Bar Group$/.test(name)||name==='Weekly Completion Chart')click=()=>open('chart',name.replace(' Activity Bar Group',' learning activity'));
   if(name==='Learner Filters')return <FilterTabs key={id} value={filter} values={['All','Active','Needs help']} onChange={changeFilter}/>;
   if(name==='Learner Saved Filters')return <FilterTabs key={id} value={filter} values={['All','New','Paid','No access','Needs help']} onChange={changeFilter}/>;
   if(name==='Message Event Filters')return <FilterTabs key={id} value={filter} values={['All events','Payments','Learning','Writing','System']} onChange={changeFilter}/>;
   if(['Payment Search','Learner Directory Search','Message Event Search'].includes(name))return <SearchBox key={id} value={query} onChange={changeQuery} placeholder={name==='Payment Search'?'Ism, @username, order ID…':name==='Learner Directory Search'?'Name, @username, Telegram ID…':'Recipient, event or order…'}/>;
   if(name==='Payment Status Filter')return <Pick key={id} label="Payment status" value={status} values={['Status: All','Paid','Pending','Cancelled','Never paid']} onChange={v=>{setStatus(v);setPage(1);}}/>;
   if(name==='Payment Method Filter')return <Pick key={id} label="Payment method" value={method} values={['Method: All','Paylov','Click','Payme','Uzum','—']} onChange={v=>{setMethod(v);setPage(1);}}/>;
   if(name==='Payments Filter Toolbar')content=<><FilterTabs value={commerceTab} values={['Transactions','Learners & access','Reconciliation']} onChange={v=>{setCommerceTab(v);setPage(1);setMobileDetail(false);}}/><div className="payment-filters"><SearchBox value={query} onChange={changeQuery} placeholder="Ism, @username, order ID…"/><Pick label="Payment status" value={status} values={['Status: All','Paid','Pending','Cancelled','Never paid']} onChange={v=>{setStatus(v);setPage(1);}}/><Pick label="Payment method" value={method} values={['Method: All','Paylov','Click','Payme','Uzum']} onChange={v=>{setMethod(v);setPage(1);}}/></div></>;
   if(name==='Payments Master Detail'&&commerceTab==='Reconciliation')content=<div className="reconcile-layout"><section><h2>Reconciliation queue <Badge>{data.cases.filter(c=>!c.resolved).length} OPEN</Badge></h2><p>Exceptions only · normal payments stay quiet</p>{data.cases.filter(c=>!c.resolved&&(c.title+c.orderId).toLowerCase().includes(query.toLowerCase())).map(c=><button className={'case-row '+(caseId===c.id?'chosen':'')} key={c.id} onClick={()=>{setCaseId(c.id);setMobileDetail(true);if(window.matchMedia("(max-width:767px)").matches)window.scrollTo({top:0});}}><AlertTriangle/><div><strong>{c.title}</strong><small>{c.orderId} · {data.learners.find(l=>l.id===c.learnerId)?.name}</small></div><ChevronRight/></button>)}{data.cases.every(c=>c.resolved)&&<div className="empty-state"><CheckCircle2/>All exceptions resolved</div>}</section><section className="purple-panel"><small>SELECTED CASE</small><h2>{currentCase.title}</h2><p>{currentCase.detail}</p><div className="inset-panel">{currentCase.orderId} · Gateway WLCM · Method Paylov<br/>{data.learners.find(l=>l.id===currentCase.learnerId)?.name}</div><Action primary onClick={()=>open('reconcile','Review evidence')} disabled={currentCase.resolved}>{currentCase.resolved?'Resolved':'Review evidence'}</Action><p className="muted">Corrections require reason + audit + conflict check</p></section></div>;
   if(name==='Payments List Panel')return <FinanceTable key={id} learners={data.learners} orders={periodOrders} mode={commerceTab} selected={selected} onSelect={selectLearner} query={query} status={status} method={method} page={page} setPage={setPage} clear={clear}/>;
   if(name==='Selected Payment Detail')return <section key={id} data-pencil-name={name} className="payment-detail purple-panel"><div className="person"><Avatar learner={p}/><div><h3>{p.name}</h3><small>{p.handle?'@'+p.handle:'ID '+p.telegram} · Telegram {p.telegram}</small></div><button className="mini-action" onClick={()=>go('Learners')}>Profil</button></div><div className="facts"><div><small>REGISTERED</small>{p.joined}</div><div><small>ORDERS</small>{data.orders.filter(o=>o.learnerId===p.id).length} {p.payment.toLowerCase()}</div><div><small>TOTAL</small>UZS {(data.orders.filter(o=>o.learnerId===p.id&&o.status==='Paid').reduce((s,o)=>s+o.amount,0)/1e6).toFixed(1)}M</div></div><div className="inset-panel"><div className="spread"><h3>Latest payment</h3><Badge>{order?.status||'Never paid'}</Badge></div><h2 className="mono">UZS {money(order?.amount||0)}</h2><p>Gateway WLCM · {order?.method||'—'}</p><dl><dt>Paid at</dt><dd>{order?.paid||'—'}</dd><dt>Order ID</dt><dd className="mono">{order?.id||'—'}</dd><dt>Gateway reference</dt><dd className="mono">{order?.reference||'—'}</dd><dt>Product</dt><dd>{p.course} · {p.access.toLowerCase()}</dd></dl></div><h3>Payment → access timeline</h3>{order?<div className="timeline">{['Order created',...(order.status==='Paid'?['Payment verified',...(p.access!=='No access'?['Lifetime access granted']:[])]:[order.status==='Cancelled'?'Order cancelled':'Awaiting payment']),...(data.events.some(e=>e.learnerId===p.id&&e.category==='Payments')?['Learner notified']:[])].map((t,i)=><div key={t}><span className="timeline-dot"/><span>{t}</span><small>{i===0?'11 Sep · 14:29':p.lastPaid}</small></div>)}</div>:<p>No payment orders for this learner.</p>}<div className="inset-panel"><strong>{order?.status==='Paid'&&p.access!=='No access'?'Reconciled':order?.status==='Paid'?'Needs review':'Payment status: '+p.payment}</strong><p>{order?.status==='Paid'&&p.access!=='No access'?'Amount, provider refs and entitlement are consistent.':p.access==='No access'?'No active entitlement.':'Inspect the learner payment timeline.'}</p></div><Action onClick={()=>{if(order)void navigator.clipboard.writeText(order.id+'\n'+order.reference).then(()=>toast.success('Payment IDs copied')).catch(()=>toast.error('Clipboard unavailable'));}} disabled={!order}><Copy size={14}/> Copy IDs</Action></section>;
   if(name==='Learner Directory List')content=<>{render(byName['Learner Directory List Header'])}<div className="directory-rows">{filteredLearners.slice((page-1)*5,page*5).map(l=><button className={'directory-row '+(selected===l.id?'chosen':'')} key={l.id} onClick={()=>selectLearner(l.id)}><Avatar learner={l}/><div><strong>{l.name}</strong><small>@{l.handle}</small></div><div className="right"><small>{l.status}</small><strong className="mono">{l.progress}%</strong></div></button>)}{filteredLearners.length===0&&<NoResults clear={clear}/>}</div><Pager page={page} size={5} total={filteredLearners.length} onChange={setPage}/></>;
   if(name==='Learner Directory List Header')content=<><span>{filteredLearners.length} learners</span><Pick label="Sort learners" value={sort} values={['Last seen ↓','Name A–Z','Progress ↓']} onChange={setSort}/></>;
   if(name==='Selected Learner Profile'||name==='Selected Learner Detail')map={...learnerMap(p),'34 lessons':Math.round(p.progress/2)+' lessons','#18':'#'+(data.learners.findIndex(l=>l.id===p.id)+18),'2 sections':p.access};
   if(name==='Selected Learner Progress Action')click=()=>open('history','Learning history');
   if(name==='Recent Learners Panel'){const overview=data.learners.filter(l=>['lr_1','lr_7','lr_8','lr_9'].includes(l.id)).filter(l=>filter==='All'||filter==='Active'&&l.access!=='No access'||filter==='Needs help'&&(l.payment==='Pending'||l.status.includes('failed')));content=<>{render(byName['Recent Learners Header'])}{render(byName['Learner Filters'])}{overview.map((l,i)=>{const names=['Madina Karimova','Jasur Akramov','Dilnoza Saidova','Azizbek Raxmatov'];const base=byName[names[['lr_1','lr_7','lr_8','lr_9'].indexOf(l.id)]+' Learner Row'];return <div key={l.id} className={'overview-person '+(selected===l.id?'chosen':'')}>{template(base,{},()=>selectLearner(l.id))}</div>;})}{overview.length===0&&<NoResults clear={clear}/>}</>;}
   if(name==='Message Event List')content=<>{render(byName['Message Event Toolbar'])}<div className="event-rows">{filteredEvents.map(e=>{const person=data.learners.find(l=>l.id===e.learnerId)!;return <button key={e.id} className={'event-row '+(e.id===eventId?'chosen':'')} onClick={()=>{setEventId(e.id);setMobileDetail(true);if(window.matchMedia("(max-width:767px)").matches)window.scrollTo({top:0});}}><span className="event-icon">{e.category==='Payments'?<CheckCircle2 size={19}/>:e.category==='System'?<AlertTriangle size={19}/>:<BookOpen size={19}/>}</span><div><strong>{e.title}</strong><small>{person.name} · @{person.handle}</small><small>{e.detail}</small></div><div className="right"><Badge>{e.status}</Badge><small>{e.time}</small></div><ChevronRight size={15}/></button>})}{filteredEvents.length===0&&<NoResults clear={clear}/>}</div><div className="pager"><span>1–{filteredEvents.length} of {data.events.length} events</span><small>Immutable event history · 90 days</small></div></>;
   if(name==='Selected Message Detail')return <section key={id} data-pencil-name={name} className="message-detail purple-panel"><small>{event.title.toUpperCase().replaceAll(' ','.')}</small><div className="spread"><h2>{event.title}</h2><Badge>{event.status.toUpperCase()}</Badge></div><div className="person"><Avatar learner={eventPerson}/><div><strong>{eventPerson.name}</strong><small>@{eventPerson.handle} · Telegram {eventPerson.telegram}</small></div></div><div className="inset-panel message-preview"><small>LEAP English · Telegram</small><p className="whitespace-pre-line">{event.body}</p><Action onClick={()=>{setCourse(eventPerson.course);go('Content');}}>Kursni ochish</Action></div><h3>Delivery timeline</h3><div className="timeline">{['Triggered','Queued',...(event.status==='Needs action'?['Delivery paused — access mismatch']:['Telegram accepted',...(event.status==='Read'?['Learner opened']:[])])].map((t,i)=><div key={t}><span className="timeline-dot"/>{t} · {event.time}{i===0?':18':i===1?':19':':20'}</div>)}</div><div className="inset-panel"><strong>Technical metadata</strong><p className="mono">event {event.id}{event.orderId?' · order '+event.orderId:''}</p></div><Action onClick={()=>{setSelected(eventPerson.id);go('Learners');}}>Open learner record <ChevronRight size={15}/></Action></section>;
   if(name==='Content Catalog Panel')content=<><h3>Catalog</h3>{courses.map(c=><button key={c} className={'catalog-row '+(course===c?'chosen':'')} onClick={()=>{setCourse(c);setUnit(1);const first=data.lessons.find(l=>l.course===c);if(first){setLesson(first);setDirty(false);}else{setLesson({...data.lessons[0],id:'lesson_'+crypto.randomUUID(),title:'New lesson',course:c,unit:1,status:'Draft',passScore:70});setDirty(true);}}}><BookOpen size={18}/><div><strong>{c}</strong><small>{c==='Foundation'?'12 units · 196 lessons':c==='Self-study Assistant'?'42 resources':c==='Advanced Vocabulary'?'84 lessons':'36 resources'}</small></div><ChevronRight size={15}/></button>)}<div className="units">{['Introductions','Daily life','Places'].map((label,i)=><button key={label} className={unit===i+1?'chosen':''} onClick={()=>{setUnit(i+1);const item=data.lessons.find(l=>l.course===course&&l.unit===i+1);if(item){setLesson(item);setDirty(false);}setMobileDetail(true);if(window.matchMedia("(max-width:767px)").matches)window.scrollTo({top:0});}}>{`Unit ${i+1} · ${label}`}<Badge>{i===0?18:16}</Badge></button>)}</div><div className="lesson-picker">{data.lessons.filter(l=>l.course===course&&l.unit===unit).map(l=><button key={l.id} className={lesson.id===l.id?'active-lesson':''} onClick={()=>{setLesson(l);setDirty(false);setMobileDetail(true);if(window.matchMedia("(max-width:767px)").matches)window.scrollTo({top:0});}}>{l.title}<small>{l.status}</small></button>)}</div><small className="catalog-version">v2026.09.11 · synced</small></>;
   if(name==='Lesson Editor Breadcrumb')content=`${course.toUpperCase()} / UNIT ${unit} / ${lesson.id==='lesson_03'?'LESSON 03':'LESSON'}`;
   if(name==='Lesson Editor Title'){content=lesson.title;click=()=>open('editLesson','Edit lesson details');}
   if(name==='Lesson Objective Value')content=lesson.objective;
   if(name==='Lesson Draft Badge Label')content=lesson.status.toUpperCase();
   if(name==='Lesson Autosave')content=dirty?'Unsaved changes':'Saved '+new Date(lesson.updated).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
   if(name==='Video lesson Editor Block Detail')content=(lesson.video||'No video attached')+' · 08:24';
   if(name==='Quick check Editor Block Detail')content=`${lesson.questions.split('\n').filter(Boolean).length} questions · pass ${lesson.passScore}%`;
   if(name==='Key phrases Editor Block Detail')content=`${lesson.phrases.split('\n').filter(Boolean).length} speaking prompts`;
   if(name==='Lesson Objective')click=()=>open('editLesson','Edit lesson objective');
   if(name.endsWith(' Editor Block')){const block=name.replace(' Editor Block','');click=()=>open('block','Edit '+block,block);attrs.draggable=true;attrs.onDragStart=()=>{draggedBlock.current=block;};attrs.onDragOver=(e:React.DragEvent)=>e.preventDefault();attrs.onDrop=(e:React.DragEvent)=>{e.preventDefault();if(draggedBlock.current){const order=[...(lesson.blockOrder||['Video lesson','Key phrases','Quick check','Lesson navigation'])];const from=order.indexOf(draggedBlock.current),to=order.indexOf(block);if(from>=0&&to>=0){order.splice(to,0,order.splice(from,1)[0]);setLesson({...lesson,blockOrder:order});setDirty(true);}draggedBlock.current=null;}};attrs.onKeyDown=(e:React.KeyboardEvent)=>{if(e.altKey&&(e.key==='ArrowUp'||e.key==='ArrowDown')){e.preventDefault();const order=[...(lesson.blockOrder||['Video lesson','Key phrases','Quick check','Lesson navigation'])];const from=order.indexOf(block),to=Math.max(0,Math.min(3,from+(e.key==='ArrowUp'?-1:1)));order.splice(to,0,order.splice(from,1)[0]);setLesson({...lesson,blockOrder:order});setDirty(true);}};attrs.title='Edit block · Drag to reorder, or Alt + Arrow Up / Down';}
   if(name==='Quiz pass score Publish Check')click=()=>open('block','Fix quiz validation','Quick check');
   if(name==='Quiz pass score Publish Check State')content=lesson.passScore>=1&&lesson.passScore<=100?'Pass':'Fix';
   if(name==='Publish Readiness Panel')map={'4 of 5 checks passed':lesson.passScore>=1?'5 of 5 checks passed':'4 of 5 checks passed','Blocked by quiz validation':lesson.passScore>=1?'Ready to publish':'Blocked by quiz validation','Pass score must be 1–100.':lesson.passScore>=1?'All lesson checks have passed.':'Pass score must be 1–100.'};
   if(name==='Publish Lesson Label')content=lesson.status==='Published'?'Published':lesson.passScore>=1?'Publish lesson':'Publish unavailable';
   if(name==='Publish Lesson Button'){disabled=lesson.passScore<1||saving||lesson.status==='Published';click=async()=>{if(dirty){if(!await saveLesson())return;toast.info('Changes saved. Select Publish lesson to publish.');return;}if(await mutate({action:'publish',lessonId:lesson.id}))setLesson({...lesson,status:'Published'});};}
   if(name==='Learning Cohort Filter')return <Pick key={id} value={cohort} label="Learning cohort" values={['All cohorts','Morning','Evening']} onChange={setCohort}/>;
   if(name==='Learning Date Filter')return <Pick key={id} value={dateRange==='Last 30 days'?'Last 7 days':dateRange} label="Learning date range" values={['Last 7 days','Last 14 days','Last 30 days']} onChange={setDateRange}/>;
   if(false){
    if(name==='Active learners Learning Stat Value')content=String(data.learners.filter(l=>l.cohort===cohort&&l.status.startsWith('Active')).length);
    if(name==='Started a lesson Funnel Value')content=data.learners.filter(l=>l.cohort===cohort&&l.progress>0).length+' learners';
    if(name==='Reached 50% Funnel Value')content=data.learners.filter(l=>l.cohort===cohort&&l.progress>=50).length+' learners';
    if(name==='Completed Funnel Value')content=data.learners.filter(l=>l.cohort===cohort&&l.progress===100).length+' learners';
    if(name==='Learning Funnel Subtitle')content=cohort+' cohort · '+dateRange;
   }
   if(/^Learning Issue \d$/.test(name)){click=()=>open('intervention','Bottleneck details',textOf(n));}
   if(/^Attention Signal \d$/.test(name))click=()=>changeFilter('Needs help');
   if(name==='Financial Date Filter Label')content=dateRange==='Last 30 days'?'Sep 01 – Sep 30':dateRange;
   if(name==='Date Range Label')content=dateRange;
   if(name==='Financial Date Filter'||name==='Date Range Control')click=()=>open('date','Reporting period');
   if(/Revenue Week |Day Column|Activity Day|Funnel Row/.test(name)){attrs.title=textOf(n)||name;click=()=>open('chart',name);}
   if(name==='Individual Finance Scroll Cue')click=()=>document.querySelector('[data-pencil-name="Individual Finance Header"]')?.scrollIntoView({behavior:'smooth'});
   if(name==='Gateway Reconciliation'||name==='Payments Health Row'){click=()=>{go('Commerce');setCommerceTab('Reconciliation');};}
   if(name==='Media Health Row')click=()=>{go('Content');open('media','Media delivery');};
   if(name==='API Health Row'||name==='Writing AI Health Row')click=()=>open('health','Delivery health');
   if(/Attention (Item|Card)|Paid, access|Pending >|Inactive after/.test(name)){click=()=>{changeFilter('Needs help');};}
   const actions:Record<string,()=>void>={
    'Export Report Button':()=>exportData('Overview'),'Financial Export':()=>exportData('Commerce'),'Financial Export Report':()=>exportData('Commerce'),'Financial Export Button':()=>exportData('Commerce'),'Export Learners Button':()=>exportData('Learners'),'Export Message Events Button':()=>exportData('Messages'),
    'Add Internal Note Button':()=>{setNote('');open('note','Add internal note');},'Manage Access Button':()=>open('access','Manage access'),
    'Open Learner Link':()=>go('Learners'),'Open Full Learner Record Button':()=>open('profile',p.name),'Open Learner Profile Button':()=>go('Learners'),
    'Import Content Button':()=>open('import','Import lessons'),'New Lesson Button':()=>{setLesson({id:'lesson_'+crypto.randomUUID(),title:'',course,unit,objective:'',passScore:70,status:'Draft',video:'',phrases:'',questions:'',updated:new Date().toISOString()});open('newLesson','New lesson');},
    'Preview Lesson Button':()=>open('preview',lesson.title),'Save Lesson Button':()=>{void saveLesson();},'Open Intervention Queue Button':()=>open('queue','Intervention queue'),
    'Refresh Messages Button':()=>{void refresh().then(()=>toast.success('Events refreshed'));},'Open Reconciliation Review Button':()=>open('reconcile','Review evidence')
   };
   if(actions[name])click=actions[name];
   if(name.includes('Export')&&n.children.some(c=>typeof c!=='string')&&!click&&/Button|Action/.test(name))click=()=>exportData(route);
  }
  if(click&&!ctx.insideButton){tag='button';attrs.type='button';attrs.onClick=click;attrs.disabled=disabled;attrs.className+=' interactive';attrs['aria-label']=name.replace(/ Button$| Link$/,'');}
  for(const k of Object.keys(attrs)){if(k==='stroke-width'||k==='stroke-linecap'||k==='stroke-linejoin'||k==='fill-rule'||k==='clip-rule'){attrs[k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=attrs[k];delete attrs[k];}if(k==='xmlns:xlink'){delete attrs[k];}}
  if(['Overview Title','Learners Title','Content Title','Financial Overview Title','Messages Title','Learning Title'].includes(name)){tag='h1';}
  let children=n.children;if(name==='Lesson Editor Panel'&&lesson.blockOrder){const blocks=n.children.filter(c=>typeof c!=='string'&&c.attrs['data-pencil-name']?.endsWith(' Editor Block')) as N[];let i=0;children=n.children.map(c=>{if(typeof c!=='string'&&c.attrs['data-pencil-name']?.endsWith(' Editor Block')){const target=lesson.blockOrder![i++]+' Editor Block';return blocks.find(b=>b.attrs['data-pencil-name']===target)||c;}return c;});}return createElement(tag,attrs,content===undefined?children.map(child=>render(child,{map,skip:ctx.skip,parent:name,insideButton:ctx.insideButton||tag==='button'})):content);
 }
 async function importFile(file:File){setModalError('');try{if(file.size>120000)throw new Error('Import must be smaller than 120 KB.');const parsed=JSON.parse(await file.text());const values=Array.isArray(parsed)?parsed:parsed.lessons;if(!Array.isArray(values))throw new Error('Expected a JSON array of lessons.');if(await mutate({action:'importLessons',lessons:values}))setModal(null);}catch(e){setModalError(e instanceof Error?e.message:'Invalid JSON');}}
 const editLessonForm=<><Field label="Lesson title"><input required maxLength={120} value={lesson.title} onChange={e=>{setLesson({...lesson,title:e.target.value});setDirty(true);}}/></Field><Field label="Course"><Pick label="Lesson course" value={lesson.course} values={courses} onChange={v=>{setCourse(v);setLesson({...lesson,course:v});setDirty(true);}}/></Field><Field label="Learning objective"><textarea required value={lesson.objective} onChange={e=>{setLesson({...lesson,objective:e.target.value});setDirty(true);}}/></Field><Field label="Unit"><input type="number" min="1" max="100" value={lesson.unit} onChange={e=>{setLesson({...lesson,unit:+e.target.value});setUnit(+e.target.value);setDirty(true);}}/></Field></>;
 return <main data-route={route} className={mobileDetail?'mobile-detail':''}>
  {error&&<div role="alert" className="error-banner"><AlertTriangle size={18}/><div><strong>{error==='Access restricted'?'Access restricted':'Couldn’t load data'}</strong><p>{error}</p></div><Action onClick={()=>void refresh()}>Retry</Action></div>}
  {!autoRefresh&&updated>0&&<div className="stale-banner">Updates paused · Last refreshed {new Date(updated).toLocaleTimeString()} <button onClick={()=>void refresh()}>Refresh now</button></div>}
  {loading&&revision===0&&<div className="loading-line" aria-label="Loading data"><Skeleton className="h-1 w-full"/></div>}
  {mobileDetail&&<button className="mobile-back action" onClick={()=>setMobileDetail(false)}><ArrowLeft size={16}/>Back to {route==='Content'?'catalog':'list'}</button>}
  {render(screens[routes[route]])}
  <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-drawer"><SheetHeader><SheetDescription>ADMIN NAVIGATION</SheetDescription><SheetTitle>Operations</SheetTitle></SheetHeader>{Object.keys(routes).map(r=><button className={r===route?'active':''} key={r} onClick={()=>go(r)}>{r}{r===route&&<Badge>CURRENT</Badge>}<ChevronRight size={18}/></button>)}<div className="drawer-account"><span className="avatar">AK</span> LEAP administrator</div></SheetContent></Sheet>
  <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!saving){setModal(null);setModalError('');}}}><DialogContent className={'admin-dialog '+(['profile','queue','preview'].includes(modal?.kind||'')?'wide':'')}><DialogHeader><DialogTitle>{modal?.title}</DialogTitle><DialogDescription>{modal?.kind==='access'?'Access changes require a reason, confirmation and a conflict check.':modal?.kind==='note'?'Private note on '+p.name+'’s canonical profile.':modal?.kind==='settings'?'Manage your workspace preferences and connections.':'LEAP English · Learning operations'}</DialogDescription></DialogHeader>
   {modalError&&<div role="alert" className="form-error">{modalError}<button onClick={()=>void refresh()}>Refresh data</button></div>}
   {modal?.kind==='search'&&<><SearchBox value={globalQuery} onChange={setGlobalQuery} placeholder="Search learners, lessons or orders…"/><div className="search-results">{data.learners.filter(l=>(l.name+l.handle+l.telegram).toLowerCase().includes(globalQuery.toLowerCase())).slice(0,6).map(l=><button key={l.id} onClick={()=>{selectLearner(l.id);go('Learners');setModal(null);}}><Avatar learner={l}/>{l.name}<small>@{l.handle}</small><ChevronRight size={16}/></button>)}{data.lessons.filter(l=>l.title.toLowerCase().includes(globalQuery.toLowerCase())).slice(0,3).map(l=><button key={l.id} onClick={()=>{setLesson(l);setCourse(l.course);setUnit(l.unit);go('Content');setModal(null);}}><BookOpen/>{l.title}<small>Lesson</small></button>)}{globalQuery&&data.orders.filter(o=>o.id.toLowerCase().includes(globalQuery.toLowerCase())).slice(0,4).map(o=><button key={o.id} onClick={()=>{selectLearner(o.learnerId,o.id);go('Commerce');setModal(null);}}>{o.id}<Badge>{o.status}</Badge></button>)}</div></>}
   {modal?.kind==='note'&&<form onSubmit={async e=>{e.preventDefault();if(await mutate({action:'note',learnerId:p.id,text:note})){setNote('');setModal(null);}}}><Field label="Internal note"><textarea autoFocus required maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Write an observation or follow-up…"/></Field><Action primary type="submit" disabled={saving||!note.trim()}>Save note</Action></form>}
   {modal?.kind==='access'&&<form onSubmit={e=>{e.preventDefault();setConfirm({action:'access',learnerId:p.id,access,reason,confirmed:true});}}><div className="inset-panel"><strong>{p.name}</strong><p>Current access: {p.access}</p></div><Field label="Access"><Pick label="Access" value={access} values={['Lifetime','2 sections','No access']} onChange={setAccess}/></Field><Field label="Reason for change"><textarea minLength={5} required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why access is changing…"/></Field><Action primary type="submit" disabled={saving||access===p.access}>Review change</Action></form>}
   {modal?.kind==='reconcile'&&<form onSubmit={e=>{e.preventDefault();setConfirm({action:'resolveCase',caseId:currentCase.id,reason,confirmed:true});}}><Badge>{currentCase.resolved?'Resolved':'Open exception'}</Badge><h3>{currentCase.title}</h3><p>{currentCase.detail}</p><dl><dt>Order</dt><dd>{currentCase.orderId}</dd><dt>Learner</dt><dd>{data.learners.find(l=>l.id===currentCase.learnerId)?.name}</dd><dt>Payment</dt><dd>{data.orders.find(o=>o.id===currentCase.orderId)?.status}</dd><dt>Amount</dt><dd>UZS {money(data.orders.find(o=>o.id===currentCase.orderId)?.amount||0)}</dd><dt>Access</dt><dd>{data.learners.find(l=>l.id===currentCase.learnerId)?.access}</dd></dl><Field label="Review note / evidence"><textarea minLength={5} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><label className="confirm-evidence"><Switch checked={reviewed} onCheckedChange={setReviewed}/>I reviewed the payment evidence and proposed correction.</label><Action primary type="submit" disabled={!reviewed||currentCase.resolved}>Review resolution</Action></form>}
   {['profile','history'].includes(modal?.kind||'')&&<><div className="person"><Avatar learner={p}/><div><h2>{p.name}</h2><small>@{p.handle} · Telegram {p.telegram}</small></div><Badge>{p.access}</Badge></div><div className="facts"><div><small>LESSONS</small>{Math.round(p.progress/2)} / 50</div><div><small>STREAK</small>{p.streak} days</div><div><small>PROGRESS</small>{p.progress}%</div></div><Progress value={p.progress}/><div className="spread"><h3>Course progress</h3><Action onClick={()=>open('access','Manage access')}>Manage access</Action></div>{[p.course,'Self-study Assistant','Advanced Vocabulary'].map((c,i)=><div key={c+i}><div className="spread"><span>{c}</span><span>{Math.max(0,p.progress-i*30)}%</span></div><Progress className="my-2" value={Math.max(0,p.progress-i*30)}/></div>)}<h3>Recent learning activity</h3>{(p.progress>0?['Present Perfect · Video','Travel plans · Writing','Unit 7 assessment']:['No learning activity yet']).map((a,i)=><div className="audit-row" key={a}><BookOpen size={17}/><span>{a}</span><Badge>{p.progress?['Completed','Passed','2 attempts'][i]:'Not started'}</Badge></div>)}<div className="spread"><h3>Internal notes</h3><Action onClick={()=>open('note','Add internal note')}><Plus size={14}/>Add note</Action></div>{p.notes.length===0?<p className="muted">No notes yet.</p>:p.notes.map((n,i)=><div key={i} className="inset-panel"><p>{n.text}</p><small>{n.author} · {new Date(n.at).toLocaleString()}</small></div>)}<h3>Audit history</h3>{data.audit.filter(a=>a.target===p.id).map(a=><div key={a.id} className="audit-row"><ShieldCheck size={16}/><span>{a.action} · {a.reason||'Internal note added'}<small>{a.actor} · {new Date(a.at).toLocaleString()}</small></span></div>)}</>}
   {['editLesson','newLesson'].includes(modal?.kind||'')&&<form onSubmit={async e=>{e.preventDefault();if(await saveLesson())setModal(null);}}>{editLessonForm}<Action primary type="submit" disabled={saving}>Save lesson</Action></form>}
   {modal?.kind==='block'&&<form onSubmit={e=>{e.preventDefault();setDirty(true);setModal(null);toast.info('Lesson updated. Save changes to keep your edits.');}}>{modal.block==='Quick check'?<><Field label="Pass score (1–100)"><input type="number" min="1" max="100" required value={lesson.passScore} onChange={e=>setLesson({...lesson,passScore:+e.target.value})}/></Field><Field label="Quiz questions (one per line)"><textarea required value={lesson.questions} onChange={e=>setLesson({...lesson,questions:e.target.value})}/></Field></>:modal.block==='Key phrases'?<Field label="Speaking prompts (one per line)"><textarea required value={lesson.phrases} onChange={e=>setLesson({...lesson,phrases:e.target.value})}/></Field>:modal.block==='Video lesson'?<><Field label="Video URL or asset filename"><input value={lesson.video} onChange={e=>setLesson({...lesson,video:e.target.value})}/></Field><p className="muted">Use your existing lesson media URL. The design’s sample video file is not included.</p></>:<><h3>Previous / Next + unit playlist</h3>{data.lessons.filter(l=>l.course===course).map(l=><div key={l.id}>{l.title} · Unit {l.unit}</div>)}<p>Navigation is generated from course and unit order.</p></>}<Action primary type="submit">Apply changes</Action></form>}
   {modal?.kind==='import'&&<><p>Import a JSON array of lesson records. New records enter the draft queue.</p><input ref={fileRef} type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}} aria-label="Import lessons JSON" disabled={saving}/><Action onClick={()=>{const sample={...data.lessons[0],id:'import_'+Date.now(),title:'Imported lesson',status:'Draft',passScore:70};const url=URL.createObjectURL(new Blob([JSON.stringify([sample],null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='leap-lesson-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Download size={15}/>Download JSON template</Action></>}
   {modal?.kind==='preview'&&<><Badge>{lesson.status}</Badge><p>{lesson.objective}</p>{/^https:\/\//.test(lesson.video)?<video controls className="lesson-video" src={lesson.video} onError={()=>setModalError('This video could not be loaded. Check the media URL.')}/>:<div className="media-placeholder"><BookOpen size={36}/><h3>{lesson.video||'No video attached'}</h3><p>The sample design does not include the video file.</p></div>}<h3>Key phrases</h3><div className="whitespace-pre-line">{lesson.phrases}</div><h3>Quick check · pass {lesson.passScore}%</h3>{lesson.questions.split('\n').filter(Boolean).map((q,i)=><Field key={q+i} label={q}><input placeholder="Type your answer"/></Field>)}<div className="spread"><Action onClick={()=>{const i=data.lessons.findIndex(l=>l.id===lesson.id);setLesson(data.lessons[(i-1+data.lessons.length)%data.lessons.length]);}}>Previous</Action><Action onClick={()=>{const i=data.lessons.findIndex(l=>l.id===lesson.id);setLesson(data.lessons[(i+1)%data.lessons.length]);}}>Next</Action></div></>}
   {modal?.kind==='date'&&<form onSubmit={e=>{e.preventDefault();if(dateStart>dateEnd){setModalError('End date must be after start date.');return;}setDateRange(`${dateStart} – ${dateEnd}`);setModal(null);toast.success('Reporting period updated');}}><Pick label="Preset date range" value={['Last 7 days','Last 14 days','Last 30 days'].includes(dateRange)?dateRange:'Last 30 days'} values={['Last 7 days','Last 14 days','Last 30 days']} onChange={v=>{setDateRange(v);setModal(null);}}/><Field label="Start date"><input type="date" required value={dateStart} onChange={e=>setDateStart(e.target.value)}/></Field><Field label="End date"><input type="date" required min={dateStart} value={dateEnd} onChange={e=>setDateEnd(e.target.value)}/></Field><Action primary type="submit">Apply date range</Action></form>}
   {modal?.kind==='settings'&&<><div className="spread"><div><h3>Automatic refresh</h3><p className="muted">Refresh operational data every minute.</p></div><Switch aria-label="Automatic refresh" checked={autoRefresh} onCheckedChange={v=>{setAutoRefresh(v);localStorage.setItem('leap-auto-refresh',String(v));}}/></div><div className="inset-panel"><h3>Data connection</h3><p>Design sample workspace · persistent database</p><p>Payment gateways and Telegram are not connected. Sample events are read-only; no live messages or payments are sent.</p></div><Action onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh now</Action><h3>Audit log</h3>{data.audit.slice(-10).reverse().map(a=><div className="audit-row" key={a.id}><ShieldCheck size={16}/><div>{a.action} · {a.target}<small>{a.actor} · {new Date(a.at).toLocaleString()}</small></div></div>)}</>}
   {modal?.kind==='account'&&<><div className="person"><span className="avatar">AK</span><div><h2>LEAP administrator</h2><small>Learning operations</small></div></div><Badge>Administrator</Badge><p>This private workspace is protected by your Sites account.</p><Action onClick={()=>open('settings','Workspace settings')}>Workspace settings</Action></>}
   {['queue','intervention'].includes(modal?.kind||'')&&<><p>{modal?.block||'Learners who need an access or learning intervention.'}</p>{data.learners.filter(l=>l.status.includes('Needs')||l.payment==='Pending'||l.status==='Inactive').slice(0,12).map(l=><button className="directory-row" key={l.id} onClick={()=>{setSelected(l.id);open('profile',l.name);}}><Avatar learner={l}/><div><strong>{l.name}</strong><small>{l.status} · {l.progress}% progress</small></div><ChevronRight size={16}/></button>)}</>}
   {modal?.kind==='chart'&&<><p>Reporting period: {dateRange} · {cohort}</p><div className="chart-detail">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><div key={d}><span>{d}</span><Progress value={[54,66,73,100,81,65,57][i]}/><strong className="mono">{[842,1023,1130,1548,1255,1006,883][i]}</strong></div>)}</div></>}
   {['health','media'].includes(modal?.kind||'')&&<><div className="inset-panel"><h3>{modal?.kind==='media'?'Media delivery':'Delivery health'}</h3><p>Design sample status. Live monitoring requires the LEAP service connections.</p></div>{['API','Payments','Media','Writing AI'].map(t=><div className="spread" key={t}><strong>{t}</strong><Badge>{t==='Media'?'3 sample failures':t==='Payments'?'2 pending':'Ready'}</Badge></div>)}<Action onClick={()=>void refresh()}>Refresh data</Action></>}
  </DialogContent></Dialog>
  <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!saving)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm {confirm?.action==='access'?'access change':'case resolution'}</AlertDialogTitle><AlertDialogDescription>{confirm?.action==='access'?`${p.name}: ${p.access} → ${access}.`:`Resolve ${currentCase.title}. ${currentCase.title==='Paid without entitlement'?'Lifetime access will be granted after checking the paid order.':''}`} Reason: {reason}. This change will be recorded in the audit log.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>Back</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={async e=>{e.preventDefault();if(confirm&&await mutate(confirm)){setConfirm(null);setModal(null);}}}>{saving?'Saving…':'Confirm change'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Toaster richColors theme="dark" position="bottom-right"/>
 </main>;
}





