'use client';
import {useState} from 'react';
export type Order={id:string;learnerId:string;sectionId:string;amountTiyin:string;currency:string;gateway:string;method:string;status:string;createdAt:string;paidAt:string|null;cancelledAt:string|null;externalId:string;gatewayOrderId:string|null;gatewayPaymentId:string|null};
export type Orders={items:Order[];total:number;limit:number;offset:number;hasMore:boolean};
export type Payment={order:Order;entitlement:{source:string;grantedAt:string;expiresAt:string|null;revokedAt:string|null;matchesPayment:boolean}|null};
export function money(order:Order){const amount=BigInt(order.amountTiyin);return `${(amount/BigInt(100)).toLocaleString('en-US')}.${String(amount%BigInt(100)).padStart(2,'0')} ${order.currency}`;}
export function OrderList({data,error,loading,selected,select,retry,offset,setOffset}:{data?:Orders;error?:string;loading:boolean;selected:string|null;select:(id:string)=>void;retry:()=>void;offset:number;setOffset:(n:number)=>void}){
 return <div className="operations-orders"><h2>Transactions</h2><p>One row per persisted payment order · Created ↓</p>{error&&<div role="alert">Refresh failed. {error}<button className="action" onClick={retry}>Retry orders</button></div>}{loading&&<p role="status">Data is updating</p>}
 <div className="operations-table-scroll"><table><thead><tr><th>Order</th><th>Learner / gateway</th><th>Created</th><th>Paid / cancelled</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody>{data?.items.map(order=><tr key={order.id} data-order-id={order.id} aria-selected={selected===order.id}><td><button className="operations-order-link" onClick={()=>select(order.id)}>{order.id}</button></td><td>{order.learnerId}<small>Gateway: {order.gateway}</small></td><td>{order.createdAt.slice(0,16).replace('T',' ')}</td><td>{(order.paidAt??order.cancelledAt)?.slice(0,16).replace('T',' ')??'—'}</td><td>{money(order)}</td><td>{order.method}</td><td>{order.status}</td></tr>)}</tbody></table></div>
 {data?.items.length===0&&!loading&&<p role="status">No payment orders match these filters.</p>}<div className="pager"><button className="action" disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous orders</button><span>{data?`${data.offset+ (data.items.length?1:0)}–${data.offset+data.items.length} of ${data.total} orders`:'Orders unavailable'}</span><button className="action" disabled={loading||!data?.hasMore||offset+25>1000000} onClick={()=>setOffset(offset+25)}>Next orders</button></div></div>;
}
export function PaymentFacts({data,error,loading,retry}:{data?:Payment;error?:string;loading:boolean;retry:()=>void}){
 const [copy,setCopy]=useState('');
 if(error)return <div role="alert">Payment detail unavailable. {error}<button className="action" onClick={retry}>Retry payment</button></div>;
 if(loading)return <p role="status">Loading payment details…</p>;
 if(!data)return <p>Select a payment order.</p>;
 const {order,entitlement}=data;
 const timeline=['Created',...(order.paidAt?['Paid']:[]),...(order.cancelledAt?['Cancelled']:[]),...(entitlement?.matchesPayment?['Access granted']:[])].join(' → ');
 return <div className="operations-payment"><h2>Payment details</h2><div className="pencil-field">Payment<div>{order.id} · {order.method} · {order.status}<br/>{money(order)}</div></div><div className="pencil-field">Timeline<div>{timeline}</div></div><dl className="readonly-facts">{[['Learner',order.learnerId],['Section',order.sectionId],['Created',order.createdAt],['Paid',order.paidAt],['Cancelled',order.cancelledAt],['Entitlement source',entitlement?.source],['Access granted',entitlement?.grantedAt],['Access expires',entitlement?.expiresAt],['Access revoked',entitlement?.revokedAt]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl><p>No provider call is performed. Entitlement timestamps are persisted observations; a grant is not proof of current access.</p><button className="action" onClick={async()=>{try{await navigator.clipboard.writeText([order.id,order.externalId,order.gatewayOrderId,order.gatewayPaymentId].filter(Boolean).join('\n'));setCopy('IDs copied');}catch{setCopy('Clipboard unavailable. Select the IDs below.');}}}>Copy IDs</button><p role="status">{copy}</p><details><summary>Payment IDs</summary><pre>{[order.id,order.externalId,order.gatewayOrderId,order.gatewayPaymentId].filter(Boolean).join('\n')}</pre></details></div>;
}
