"use client";
import {useState} from 'react';
import {Bell,Settings,Search,Sun,Moon,Menu,LayoutDashboard,Users,Library,CreditCard,ChartNoAxesCombined,MessageSquare,ChevronRight} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
const entries=[['Overview',LayoutDashboard],['Learners',Users],['Content',Library],['Commerce',CreditCard],['Learning',ChartNoAxesCombined],['Messages',MessageSquare]] as const;
export type PencilSection=typeof entries[number][0];
export function PencilNavigation({section,go,light,toggle,open,username}:{section:PencilSection;go:(s:PencilSection)=>void;light:boolean;toggle:()=>void;open:(s:'settings'|'account'|'search')=>void;username:string}){
 const [mobile,setMobile]=useState(false);
 const account=username.slice(0,2).toUpperCase();
 const utilities=<><button aria-label="Search everything" onClick={()=>{setMobile(false);open('search');}}><Search size={18}/></button><button aria-label="Notifications" onClick={()=>{setMobile(false);go('Messages');}}><Bell size={18}/></button><button aria-label="Settings" onClick={()=>{setMobile(false);open('settings');}}><Settings size={18}/></button></>;
 const brand=<div className="pencil-brand"><span>L</span><div><strong>LEAP English</strong><small>Learning operations</small></div></div>;
 return <><header className="pencil-navigation" data-pencil-canonical="O3oJS8">{brand}<nav aria-label="Primary navigation">{entries.map(([route])=><button key={route} aria-label={route} aria-current={section===route?'page':undefined} onClick={()=>go(route)}>{route}</button>)}</nav><div className="pencil-utilities">{utilities}<button className="pencil-account" aria-label="Admin profile" onClick={()=>open('account')}>{account}</button><button className="pencil-theme" aria-label={`Switch to ${light?'dark':'light'} mode`} onClick={toggle}>{light?<Moon size={18}/>:<Sun size={18}/>}</button></div><button className="pencil-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></button></header>
 <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="pencil-mobile"><div className="pencil-mobile-brand">{brand}</div><div className="pencil-mobile-body"><SheetHeader><SheetDescription>ADMIN NAVIGATION</SheetDescription><SheetTitle>Operations</SheetTitle></SheetHeader><button className="pencil-account" aria-label="Admin profile" onClick={()=>{setMobile(false);open('account');}}>{account}</button><nav aria-label="Mobile navigation">{entries.map(([route,Icon])=><button key={route} aria-current={section===route?'page':undefined} onClick={()=>{setMobile(false);go(route);}}><Icon size={18}/>{route}{section===route?<small>CURRENT</small>:<ChevronRight size={16}/>}</button>)}</nav><div className="pencil-mobile-utilities">{utilities}<button aria-label={`Switch to ${light?'dark':'light'} mode`} onClick={toggle}>{light?<Moon size={18}/>:<Sun size={18}/>}</button></div><aside><strong>Below 768 px</strong><p>Learners: list → full-page profile</p><p>Content: catalog → editor → publish</p><p>Learning: analytics, then insights stack</p><p>Messages: events → full-page detail</p></aside></div></SheetContent></Sheet></>;
}
