"use client";
import {useState} from 'react';
import {Bell,Settings,Search,Sun,Moon,Menu,LayoutDashboard,Users,Library,CreditCard,Bot,MessageSquare,ChevronRight,LogOut,RefreshCw} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
const entries=[['Overview','Boshqaruv',LayoutDashboard],['Learners','Foydalanuvchilar',Users],['Content','Content',Library],['Commerce','To‘lovlar',CreditCard],['AI','AI',Bot],['Messages','Xabarnoma',MessageSquare]] as const;
export type PushdaySection=typeof entries[number][0];
export function PushdayNavigation({section,go,light,toggle,open,username,logout,refresh}:{section:PushdaySection;go:(s:PushdaySection)=>void;light:boolean;toggle:()=>void;open:(s:'settings'|'account'|'search')=>void;username:string;logout:()=>void;refresh:()=>void}){
 const [mobile,setMobile]=useState(false);
 const account=username.slice(0,2).toUpperCase();
 const utilities=<><button aria-label="Search everything" onClick={()=>{setMobile(false);open('search');}}><Search size={18}/></button><button aria-label="Notifications" onClick={()=>{setMobile(false);go('Messages');}}><Bell size={18}/></button><button aria-label="Settings" onClick={()=>{setMobile(false);open('settings');}}><Settings size={18}/></button></>;
 const brand=<div className="pd-brand"><span>L</span><div><strong>LEAP English</strong><small>ADMIN PANEL</small></div></div>;
 return <><header className="pd-topbar">{brand}<nav aria-label="Primary navigation">{entries.map(([route,label,Icon])=><button key={route} aria-label={label} aria-current={section===route?'page':undefined} onClick={()=>go(route)}><Icon size={15}/><span>{label}</span></button>)}</nav><div className="pd-utilities">{utilities}<button aria-label="Ma’lumotni yangilash" onClick={refresh}><RefreshCw size={17}/></button><button className="pd-account" aria-label="Admin profile" onClick={()=>open('account')}>{account}</button><button className="pd-theme" aria-label={`Switch to ${light?'dark':'light'} mode`} onClick={toggle}>{light?<Moon size={17}/>:<Sun size={17}/>}</button><button className="pd-logout" aria-label="Sign out" onClick={logout}><LogOut size={17}/></button></div><button className="pd-menu" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu/></button></header>
 <Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="pd-mobile"><div className="pd-mobile-brand">{brand}</div><div className="pd-mobile-body"><SheetHeader><SheetDescription>LEAP ADMIN</SheetDescription><SheetTitle>Bo‘limlar</SheetTitle></SheetHeader><button className="pd-account" aria-label="Admin profile" onClick={()=>{setMobile(false);open('account');}}>{account}</button><nav aria-label="Mobile navigation">{entries.map(([route,label,Icon])=><button key={route} aria-current={section===route?'page':undefined} onClick={()=>{setMobile(false);go(route);}}><Icon size={18}/>{label}{section===route?<small>FAOL</small>:<ChevronRight size={16}/>}</button>)}</nav><div className="pd-mobile-utilities">{utilities}<button aria-label="Ma’lumotni yangilash" onClick={refresh}><RefreshCw size={18}/></button><button aria-label={`Switch to ${light?'dark':'light'} mode`} onClick={toggle}>{light?<Moon size={18}/>:<Sun size={18}/>}</button><button aria-label="Sign out" onClick={logout}><LogOut size={18}/></button></div></div></SheetContent></Sheet></>;
}
