"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type ReportingResource='learners'|'payments'|'notifications';
export const reportingSorts={learners:{telegramUserId:'Telegram ID',createdAt:'Registration date',lastSeenAt:'Last seen',username:'Username'},payments:{createdAt:'Order creation',amountTiyin:'Amount (tiyin)',status:'Status'},notifications:{createdAt:'Created',kind:'Kind'}};
export function ReportingDialog({mode,resource,query,onApply,onClose}:{mode:'Date range'|'Sort & paginate'|'Export report';resource:ReportingResource;query:string;onApply:(v:Record<string,string>)=>void;onClose:()=>void}){
 const current=new URLSearchParams(query);
 const [start,setStart]=useState(current.get('start')??''),[end,setEnd]=useState(current.get('end')??'');
 const [sort,setSort]=useState(current.get('sort')??(resource==='learners'?'telegramUserId':'createdAt')),[direction,setDirection]=useState(current.get('direction')??(resource==='learners'?'asc':'desc'));
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState('');
 async function download(){setBusy(true);setError('');setResult('');try{const params=new URLSearchParams(query);params.set('resource',resource);const response=await fetch('/api/admin/export?'+params,{cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(12000)});if(response.status===401){window.location.replace('/login');return;}const data=await response.json();if(!response.ok)throw new Error(data.error?.message??'Export failed.');const url=URL.createObjectURL(new Blob(['\uFEFF',data.csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`leap-${resource}-page.csv`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setResult(`Downloaded ${data.rowCount} records from this page; ${data.total} matching records in total.`);}catch(e){setError(e instanceof Error?e.message:'Export failed.');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="admin-dialog pencil-dialog"><DialogHeader><DialogTitle>{mode}</DialogTitle><DialogDescription>{mode==='Date range'?'Filter record creation dates, inclusive UTC calendar days. Dashboard lifetime totals and unavailable charts do not change.':mode==='Sort & paginate'?'Server sorting preserves active filters and resets to the first page.':'Download the current filtered server page, not the entire dataset. No provider operation is performed.'}</DialogDescription></DialogHeader>
 {mode==='Date range'?<><label className="pencil-field">Start date (UTC)<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="pencil-field">End date (UTC)<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></>:mode==='Sort & paginate'?<><label className="pencil-field">Sort field<select aria-label="Sort field" value={sort} onChange={e=>setSort(e.target.value)}>{Object.entries(reportingSorts[resource]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="pencil-field">Sort direction<select aria-label="Sort direction" value={direction} onChange={e=>setDirection(e.target.value)}><option value="asc">Ascending ↑</option><option value="desc">Descending ↓</option></select></label></>:<><div className="pencil-field">Format<div>CSV · UTF-8 · spreadsheet formula-safe</div></div><div className="pencil-field">Scope<div>{resource} · current server page · offset {current.get('offset')??0} · up to {current.get('limit')??25} rows</div></div></>}
 {error&&<p role="alert">{error}</p>}{result&&<p role="status">{result}</p>}<div className="pencil-dialog-actions"><button disabled={busy} onClick={onClose}>Cancel</button><button className="pencil-primary" disabled={busy} onClick={()=>{if(mode==='Export report'){void download();return;}if(mode==='Date range'){if(start&&end&&start>end){setError('End date must be on or after start date.');return;}onApply({start,end});}else onApply({sort,direction});onClose();}}>{busy?'Downloading…':mode==='Export report'?'Download CSV':mode==='Date range'?'Apply range':'Apply sorting'}</button></div></DialogContent></Dialog>;
}
