export type Learner={id:string;name:string;handle:string;telegram:string;joined:string;progress:number;streak:number;access:string;status:string;method:string;amount:number;payment:string;lastPaid:string;course:string;cohort:string;notes:{text:string;at:string;author:string}[]};
export type Lesson={blockOrder?:string[];id:string;title:string;course:string;unit:number;objective:string;passScore:number;status:string;video:string;phrases:string;questions:string;updated:string};
export type MessageEvent={id:string;title:string;learnerId:string;category:string;detail:string;status:string;time:string;body:string;orderId:string};
export type Order={id:string;learnerId:string;amount:number;method:string;status:string;created:string;paid:string;reference:string};
export type Case={id:string;title:string;learnerId:string;orderId:string;detail:string;resolved:boolean};
export type AdminData={learners:Learner[];lessons:Lesson[];events:MessageEvent[];orders:Order[];cases:Case[];audit:{id:string;at:string;actor:string;action:string;target:string;reason:string}[]};
export const initials=(name:string)=>name.split(' ').map(s=>s[0]).slice(0,2).join('');
export const money=(n:number)=>new Intl.NumberFormat('en-US').format(n);
export function seedData():AdminData{
 const known=[['Madina Karimova','madina_k','68','Lifetime','Paylov','Paid','1200000','Active now'],['Aziz Aliyev','aziz_a','0','No access','—','Never paid','0','New · today'],['Dilnoza Ismailova','dilnoza','42','Lifetime','Paylov','Paid','1200000','Active · 2h'],['Behruz Rustamov','behruz_r','18','No access','Click','Pending','1200000','Needs access'],['Nodira Saidova','nodira_s','81','2 sections','Paylov','Paid','2400000','Active · 1d'],['Javohir Olimov','','24','No access','Uzum','Cancelled','1200000','Inactive'],['Jasur Akramov','jasur_a','42','No access','Click','Pending','1200000','Payment pending'],['Dilnoza Saidova','dilnoza_s','81','Lifetime','Payme','Paid','1200000','Writing reviewed'],['Azizbek Raxmatov','azizbek_r','24','Lifetime','Uzum','Paid','1200000','Reminder failed'],['Madina N.','madina_n','32','No access','Paylov','Paid','1200000','Needs access']];
 const learners:Learner[]=known.map((a,i)=>({id:'lr_'+(i+1),name:a[0],handle:a[1],telegram:String(649204118+i*42831),joined:`2026-09-${String(11-Math.min(i,10)).padStart(2,'0')}`,progress:+a[2],streak:i===0?7:i%8,access:a[3],method:a[4],payment:a[5],amount:+a[6],status:a[7],lastPaid:a[5]==='Paid'?`${11-Math.min(i,10)} Sep ${i===0?'14:32':'09:18'}`:'—',course:'Foundation',cohort:i%2?'Evening':'Morning',notes:[]}));
 const first=['Malika','Sardor','Shahnoza','Akmal','Diyor','Sevara','Umida','Islom','Zarina','Bobur','Kamola','Shahzod'];const last=['Rahimov','Karimova','Tursunov','Ergasheva','Qodirov','Yusupova','Sobirov'];
 for(let i=10;i<289;i++){const name=first[i%12]+' '+last[Math.floor(i/12)%7];learners.push({id:'lr_'+(i+1),name,handle: name.toLowerCase().replace(' ','_')+'_'+i,telegram:String(650000000+i*2301),joined:`2026-${i<100?'09':'08'}-${String(1+i%28).padStart(2,'0')}`,progress:i*7%101,streak:i%14,access:i<60?'Lifetime':'No access',status:i<214?'Active · 1d':'Inactive',method:i<60?['Paylov','Click','Payme','Uzum'][i%4]:'—',amount:i<60?1200000:0,payment:i<60?'Paid':'Never paid',lastPaid:i<60?'08 Sep 17:05':'—',course:['Foundation','Self-study Assistant','Advanced Vocabulary'][i%3],cohort:i%2?'Evening':'Morning',notes:[]});}
 const ids=['pay_01J7K8','pay_01J7JZ','pay_01J7HY','pay_01J7GX','pay_01J7FW','pay_01J7D2'];const person=[0,2,3,5,4,9];
 const orders:Order[]=Array.from({length:67},(_,i)=>{const p=learners[i<6?person[i]:i];const status=i<6?p.payment:i<55?'Paid':i<60?'Pending':'Cancelled';return {id:ids[i]||'pay_01J'+String(8000+i),learnerId:p.id,amount:p.amount||1200000,method:p.method==='—'?'Paylov':p.method,status,created:`2026-09-${String(11-i%10).padStart(2,'0')}T14:29:00+05:00`,paid:status==='Paid'?p.lastPaid:'—',reference:i===0?'wlcm_982745':'wlcm_'+(982745-i*73)};});
 const lessons:Lesson[]=[{id:'lesson_03',title:'Daily routines',course:'Foundation',unit:1,objective:'Describe a typical weekday using present simple.',passScore:0,status:'In review',video:'Daily routines.mp4',phrases:'How do you start your day?\nDescribe your morning routine.\nWhat time do you leave home?',questions:'What time do you wake up?\nWhich verb describes a daily habit?',updated:'2026-09-11T10:42:00+05:00'},...['Introductions','Daily life','Places','Present Perfect','My Weekend','Travel plans'].map((title,i)=>({id:'lesson_'+(i+4),title,course:i>3?'Advanced Vocabulary':'Foundation',unit:1+i%3,objective:'Build confidence with practical English.',passScore:70,status:'Published',video:'',phrases:'Tell us about your experience.',questions:'Choose the correct answer.',updated:'2026-09-11T09:00:00+05:00'}))];
 const events:MessageEvent[]=[['Payment confirmed','lr_1','Payments','Foundation lifetime access granted','Delivered','14:33','To‘lov tasdiqlandi!\nFoundation kursiga lifetime access ochildi. Endi darsni davom ettirishingiz mumkin.'],['Writing feedback ready','lr_3','Writing','My Weekend · score 82%','Read','13:08','Your writing feedback is ready. My Weekend: 82%.'],['Payment pending reminder','lr_4','Payments','Order pending for 24 hours','Delivered','11:42','Your payment is still pending. Check the order in your account.'],['New lesson available','lr_5','Learning','Advanced Vocabulary · Unit 4','Read','10:17','A new lesson is ready in Advanced Vocabulary.'],['Access sync warning','lr_10','System','Paid order has no entitlement','Needs action','09:55','Payment pay_01J7D2 is paid but no entitlement was found.'],['Streak milestone','lr_2','Learning','7 day learning streak','Read','Yesterday','Congratulations on your seven day learning streak!']].map((a,i)=>({id:'evt_'+(i===0?'7K18':'7K'+(19+i)),title:a[0],learnerId:a[1],category:a[2],detail:a[3],status:a[4],time:a[5],body:a[6],orderId:i===0?'pay_01J7K8':i===4?'pay_01J7D2':''}));
 return {learners,orders,lessons,events,cases:[{id:'case_1',title:'Paid without entitlement',learnerId:'lr_10',orderId:'pay_01J7D2',detail:'Order paid 11 Sep 09:02 · amount matched · entitlement missing',resolved:false},{id:'case_2',title:'Amount mismatch',learnerId:'lr_3',orderId:'pay_01J7JZ',detail:'Expected UZS 1,200,000. Provider evidence requires a review.',resolved:false},{id:'case_3',title:'Unknown provider reference',learnerId:'lr_4',orderId:'pay_01J7HY',detail:'Unknown provider reference: event wlcm_77103',resolved:false}],audit:[]};
}

